/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package elquinto;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JLabel;

/**
 *
 * @author tomaa
 */
public class ElQuintoUI extends javax.swing.JFrame {

    /**
     * Creates new form ElQuintoUI
     */
    public ElQuintoUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numero1 = new javax.swing.JLabel();
        numero2 = new javax.swing.JLabel();
        numero4 = new javax.swing.JLabel();
        numero3 = new javax.swing.JLabel();
        numero7 = new javax.swing.JLabel();
        numero6 = new javax.swing.JLabel();
        numero9 = new javax.swing.JLabel();
        numero8 = new javax.swing.JLabel();
        numero10 = new javax.swing.JLabel();
        numero5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        aleatorio1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(217, 238, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numero1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numero1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero1.setText("x");
        numero1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 164, 67, 57));

        numero2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numero2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero2.setText("x");
        numero2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(numero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 164, 67, 57));

        numero4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numero4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero4.setText("x");
        numero4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(numero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 164, 67, 57));

        numero3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numero3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero3.setText("x");
        numero3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(numero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 164, 67, 57));

        numero7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numero7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero7.setText("x");
        numero7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(numero7, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 227, 67, 57));

        numero6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numero6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero6.setText("x");
        numero6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(numero6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 227, 67, 57));

        numero9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numero9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero9.setText("x");
        numero9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(numero9, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 227, 67, 57));

        numero8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numero8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero8.setText("x");
        numero8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(numero8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 227, 67, 57));

        numero10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numero10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero10.setText("x");
        numero10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(numero10, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 227, 67, 57));

        numero5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numero5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero5.setText("x");
        numero5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(numero5, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 164, 67, 57));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 130, 40));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 40));

        jButton2.setText("GENERAR");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 100, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("NUMERO ALEATORIO");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("GENERAR CARTILLA");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 40));

        aleatorio1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        aleatorio1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        aleatorio1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        aleatorio1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(aleatorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 200, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JLabel[] etiquetas = {numero1, numero2, numero3, numero4, numero5, numero6, numero7, numero8, numero9, numero10};
        for (JLabel etiqueta : etiquetas) {
            etiqueta.setForeground(Color.black);
        }
        int comprobarA;
        int[] numeros = new int[10];
        boolean repetido;
        for (int i = 0; i < numeros.length; i++) {
            do {
                comprobarA = (int) (1 + Math.random() * 20);
                repetido = false;
                for (int j = 0; j < i; j++) {
                    if (comprobarA == numeros[j]) {
                        repetido = true;
                        break; // Salir del bucle si se encuentra un duplicado
                    }
                }
            } while (repetido);
            numeros[i] = comprobarA; // Asignar el valor único encontrado
            System.out.println(numeros[i]);
        }

        

        // Asignar los números a las etiquetas
        for (int i = 0; i < etiquetas.length; i++) {
            etiquetas[i].setText(String.valueOf(numeros[i]));
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    ArrayList<Integer> numeros = new ArrayList<>();
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        /* int numero;
        String numeroString;
        if (contador != 3){
        numero = (int) (1 + Math.random() * 20);
        numeroString = String.valueOf(numero);
        aleatorio1.setText(aleatorio1.getText() + numeroString + " ");   
        }
        int contador = 0;
        
        if (contador == 3) {
            aleatorio1.setText("");
            numero = (int) (1 + Math.random() * 20);
            numeroString = String.valueOf(numero);
            aleatorio1.setText(aleatorio1.getText() + numeroString + " ");
            contador = 0;
        }contador++;
        JLabel[] etiquetas = {numero1, numero2, numero3, numero4, numero5, numero6, numero7, numero8, numero9, numero10};
        for (JLabel etiqueta : etiquetas) {
            if (etiqueta.equals(aleatorio1)) {
                etiqueta.setText("");
            }
        }*/

        JLabel[] etiquetas = {numero1, numero2, numero3, numero4, numero5, numero6, numero7, numero8, numero9, numero10};

        if (numeros.size() == 3) {
            numeros.clear();
            aleatorio1.setText("");
        }
        numeros.add((int) (1 + Math.random() * 20));
        
        switch (numeros.size()){
            case 1 : {
                aleatorio1.setText(String.valueOf(numeros.get(0)));
            }
            case 2 : {
                aleatorio1.setText(String.valueOf(numeros.get(0) + " " + numeros.get(1)));  
            }
            case 3 : {
                aleatorio1.setText(String.valueOf(numeros.get(0) + " " + numeros.get(1) + " " + numeros.get(2)));  
            }
        }
            
        

        for (int i = 0; i < etiquetas.length; i++) {
            for (int j = 0; j < 10; j++) {
                if (String.valueOf(numeros.get(i)).equals(etiquetas[j].getText())) {
                    etiquetas[j].setForeground(Color.white);
                }
            }
        }

        /*
        aleatorio1.setText(String.valueOf(numeros.get(0)));    
        
        
        for (JLabel etiqueta : etiquetas) {
          String valor = aleatorio1.getText();
           String trim = valor.trim();
            if (etiqueta.getText().equals(trim)) {
                etiqueta.setForeground(Color.red);
            }
        }*/

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElQuintoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElQuintoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElQuintoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElQuintoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElQuintoUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aleatorio1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel numero1;
    private javax.swing.JLabel numero10;
    private javax.swing.JLabel numero2;
    private javax.swing.JLabel numero3;
    private javax.swing.JLabel numero4;
    private javax.swing.JLabel numero5;
    private javax.swing.JLabel numero6;
    private javax.swing.JLabel numero7;
    private javax.swing.JLabel numero8;
    private javax.swing.JLabel numero9;
    // End of variables declaration//GEN-END:variables
}
