/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author tomaa
 */
public class CalculadoraUI extends javax.swing.JFrame {
    public float primernumero;
    public float segundonumero;
    public String operador;
    
    

    /**
     * Creates new form CalculadoraUI
     */
    public CalculadoraUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        casilla = new javax.swing.JLabel();
        siete = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        uno = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        decimal = new javax.swing.JButton();
        division = new javax.swing.JButton();
        multiplicacion = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        resultado = new javax.swing.JButton();
        borrarOperacion = new javax.swing.JButton();
        caritaTriste = new javax.swing.JButton();
        caritaSonriente1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        casilla.setBackground(new java.awt.Color(255, 255, 255));
        casilla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        casilla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        casilla.setOpaque(true);
        jPanel1.add(casilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 42));

        siete.setText("7");
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });
        jPanel1.add(siete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 42, 42));

        ocho.setText("8");
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });
        jPanel1.add(ocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 42, 42));

        nueve.setText("9");
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });
        jPanel1.add(nueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 42, 42));

        cuatro.setText("4");
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });
        jPanel1.add(cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 42, 42));

        cinco.setText("5");
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });
        jPanel1.add(cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 42, 42));

        seis.setText("6");
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });
        jPanel1.add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 42, 42));

        dos.setText("2");
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });
        jPanel1.add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 42, 42));

        tres.setText("3");
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });
        jPanel1.add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 42, 42));

        uno.setText("1");
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });
        jPanel1.add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 42, 42));

        cero.setText("0");
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });
        jPanel1.add(cero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 42, 42));

        decimal.setText(",");
        decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalActionPerformed(evt);
            }
        });
        jPanel1.add(decimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 42, 42));

        division.setText("/");
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });
        jPanel1.add(division, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 99, 42));

        multiplicacion.setText("*");
        multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacionActionPerformed(evt);
            }
        });
        jPanel1.add(multiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 99, 42));

        resta.setText("-");
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });
        jPanel1.add(resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 99, 42));

        suma.setText("+");
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });
        jPanel1.add(suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 99, 42));

        resultado.setText("=");
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });
        jPanel1.add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 99, 43));

        borrarOperacion.setText("C");
        borrarOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarOperacionActionPerformed(evt);
            }
        });
        jPanel1.add(borrarOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 42, 42));

        caritaTriste.setText(":(");
        caritaTriste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caritaTristeActionPerformed(evt);
            }
        });
        jPanel1.add(caritaTriste, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 42, 42));

        caritaSonriente1.setText(":)");
        caritaSonriente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caritaSonriente1ActionPerformed(evt);
            }
        });
        jPanel1.add(caritaSonriente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 42, 42));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrarOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarOperacionActionPerformed
        this.casilla.setText("");
    }//GEN-LAST:event_borrarOperacionActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        // RESULTADO DE LAS OPERACIONES
        this.segundonumero=Float.parseFloat(this.casilla.getText());
        
        switch (operador) {
            case "+":{
                this.casilla.setText(eliminarCero(this.primernumero+this.segundonumero));
                break;
            }
            case "-":{
                this.casilla.setText(eliminarCero(this.primernumero-this.segundonumero));
                break;
            }
            case "*":{
                this.casilla.setText(eliminarCero(this.primernumero*this.segundonumero));
                break;
            }
            case "/":{
                this.casilla.setText(eliminarCero(this.primernumero/this.segundonumero));
                break;
            }
        }
    }//GEN-LAST:event_resultadoActionPerformed

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
        // CUANDO SE PRESIONE EL BOTON, SE HARA UNA SUMA
        this.primernumero=Float.parseFloat(this.casilla.getText());
        this.operador="+";
        this.casilla.setText("");
        
    }//GEN-LAST:event_sumaActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed
        // CUANDO SE PRESIONE EL BOTON, SE HARA UNA resta
        this.primernumero=Float.parseFloat(this.casilla.getText());
        this.operador="-";
        this.casilla.setText("");
    }//GEN-LAST:event_restaActionPerformed

    private void multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacionActionPerformed
        // CUANDO SE PRESIONE EL BOTON, SE HARA UNA MULTIPLICACION
        
        this.primernumero=Float.parseFloat(this.casilla.getText());
        this.operador="*";
        this.casilla.setText("");
    }//GEN-LAST:event_multiplicacionActionPerformed

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
        // ACCION AL SELECCIONAR CASILLA "cero"
        if (this.casilla.getText().contains(":)") || this.casilla.getText().contains(":(")) {
            this.casilla.setText("");
        }
        this.casilla.setText(this.casilla.getText()+"0");
    }//GEN-LAST:event_ceroActionPerformed

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        // ACCION AL SELECCIONAR CASILLA "uno"
        if (this.casilla.getText().contains(":)") || this.casilla.getText().contains(":(")) {
            this.casilla.setText("");
        }
        this.casilla.setText(this.casilla.getText()+"1");
    }//GEN-LAST:event_unoActionPerformed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
        // ACCION AL SELECCIONAR CASILLA "dos"
        if (this.casilla.getText().contains(":)") || this.casilla.getText().contains(":(")) {
            this.casilla.setText("");
        }
        this.casilla.setText(this.casilla.getText()+"2");
    }//GEN-LAST:event_dosActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        // ACCION AL SELECCIONAR CASILLA "tres"
        if (this.casilla.getText().contains(":)") || this.casilla.getText().contains(":(")) {
            this.casilla.setText("");
        }
        this.casilla.setText(this.casilla.getText()+"3");
    }//GEN-LAST:event_tresActionPerformed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
        // ACCION AL SELECCIONAR CASILLA "cuatro"
        if (this.casilla.getText().contains(":)") || this.casilla.getText().contains(":(")) {
            this.casilla.setText("");
        }
        this.casilla.setText(this.casilla.getText()+"4");
    }//GEN-LAST:event_cuatroActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        // ACCION AL SELECCIONAR CASILLA "cinco"
        if (this.casilla.getText().contains(":)") || this.casilla.getText().contains(":(")) {
            this.casilla.setText("");
        }
        this.casilla.setText(this.casilla.getText()+"5");
    }//GEN-LAST:event_cincoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        // ACCION AL SELECCIONAR CASILLA "seis"
        if (this.casilla.getText().contains(":)") || this.casilla.getText().contains(":(")) {
            this.casilla.setText("");
        }
        this.casilla.setText(this.casilla.getText()+"6");
    }//GEN-LAST:event_seisActionPerformed

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteActionPerformed
        // ACCION AL SELECCIONAR CASILLA "siete"
        if (this.casilla.getText().contains(":)") || this.casilla.getText().contains(":(")) {
            this.casilla.setText("");
        }
        this.casilla.setText(this.casilla.getText()+"7");
    }//GEN-LAST:event_sieteActionPerformed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
        // ACCION AL SELECCIONAR CASILLA "ocho"
        if (this.casilla.getText().contains(":)") || this.casilla.getText().contains(":(")) {
            this.casilla.setText("");
        }
        this.casilla.setText(this.casilla.getText()+"8");
    }//GEN-LAST:event_ochoActionPerformed

    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveActionPerformed
        // ACCION AL SELECCIONAR CASILLA "nueve"
        if (this.casilla.getText().contains(":)") || this.casilla.getText().contains(":(")) {
            this.casilla.setText("");
        }
        this.casilla.setText(this.casilla.getText()+"9");
    }//GEN-LAST:event_nueveActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
        // CUANDO SE PRESIONE EL BOTON, SE HARA UNA DIVISION
        this.primernumero=Float.parseFloat(this.casilla.getText());
        this.operador="/";
        this.casilla.setText("");
    }//GEN-LAST:event_divisionActionPerformed

    private void decimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalActionPerformed
        // CUANDO SE PRESIONE, EL NUMEROPO ENTERO PASARÁ A DECIMAL
        if (!this.casilla.getText().contains(".")) {
            this.casilla.setText(this.casilla.getText()+".");
        }
    }//GEN-LAST:event_decimalActionPerformed

    private void caritaTristeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caritaTristeActionPerformed
        // EASTER EGG CARITA TRISTE
        casilla.setText(":(");
        
        
        
    }//GEN-LAST:event_caritaTristeActionPerformed

    private void caritaSonriente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caritaSonriente1ActionPerformed
        // TODO add your handling code here:
        casilla.setText(":)");
        
    }//GEN-LAST:event_caritaSonriente1ActionPerformed

    public String eliminarCero(float resultado){
        String resultadoActualizado;
        if (resultado%1==0) {
            resultadoActualizado=String.valueOf((int)resultado);
        }
        else{
            resultadoActualizado=Float.toString(resultado);
        }
        return resultadoActualizado;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarOperacion;
    private javax.swing.JButton caritaSonriente1;
    private javax.swing.JButton caritaTriste;
    private javax.swing.JLabel casilla;
    private javax.swing.JButton cero;
    private javax.swing.JButton cinco;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton decimal;
    private javax.swing.JButton division;
    private javax.swing.JButton dos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton multiplicacion;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JButton resta;
    private javax.swing.JButton resultado;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton suma;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    // End of variables declaration//GEN-END:variables
}
