/*1*/SELECT NOMBR_PROV FROM PROVEEDOR;
/*2*/SELECT CIUD FROM CLIENTE;
/*3*/SELECT IDENT_CLIENT, APELL1, NOMBR_CLIENT,CIUD FROM CLIENTE WHERE  CIUD LIKE "MADRID";
/*4*/SELECT * FROM ARTICULO WHERE PESO >500;
/*5*/SELECT * FROM ARTICULO WHERE PREC_VENT >= (PREC_COMPR*2);
/*6*/SELECT * FROM ARTICULO WHERE COLOR = "ROJO" AND PESO > 100;
/*7*/SELECT * FROM ARTICULO WHERE COLOR = "ROJO" OR PESO > 500;
/*8*/SELECT * FROM ARTICULO WHERE COLOR != "ROJO" AND PESO <= 500;
/*9*/SELECT * FROM ARTICULO WHERE (COLOR = "ROJO" AND PESO > 100) OR COLOR= "VERDE";
/*10*/SELECT * FROM ARTICULO WHERE prec_compr AND prec_vent BETWEEN 12 AND 18;
/*11*/SELECT * FROM ARTICULO WHERE COLOR LIKE "ROJO" OR COLOR LIKE"VERDE";
/*12*/ SELECT * FROM ARTICULO WHERE COLOR IS NULL;
/*13*/SELECT * FROM CLIENTE WHERE APELL1 LIKE "RO%";
/*14*/ SELECT * FROM CLIENTE WHERE APELL1 LIKE "DU%" AND APELL1 LIKE"%T";
/*15*/ SELECT * FROM ARTICULO ORDER BY PESO;
/*16*/ SELECT * FROM ARTICULO WHERE PESO < 100 ORDER BY PESO DESC , PREC_COMPR DESC;
/*17*/ SELECT IDENT_ARTIC, (PREC_VENT-PREC_COMPR) AS beneficio FROM ARTICULO WHERE PREC_COMPR > 12;
/*18*/
    