/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crudbiblioteca;

import java.io.File;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaView;
import javafx.stage.Stage;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tomaa
 */
public class UI extends javax.swing.JFrame {

    Libro libros = new Libro();
    Enciclopedia enciclopedia = new Enciclopedia();
    BibliotecaManager gestor = new BibliotecaManager();
    boolean accion;

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        INSERTAR = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        numPagInsertar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        isbnInsertar = new javax.swing.JTextField();
        tituloInsertar = new javax.swing.JTextField();
        categoriaInsertar = new javax.swing.JTextField();
        precioInsertar = new javax.swing.JTextField();
        insertarAccion = new javax.swing.JButton();
        atrasAnadir = new javax.swing.JButton();
        LEER = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        numPagLeer = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        isbnLeer = new javax.swing.JTextField();
        tituloLeer = new javax.swing.JTextField();
        categoriaLeer = new javax.swing.JTextField();
        precioLeer = new javax.swing.JTextField();
        leerAccion = new javax.swing.JButton();
        atrasLeer = new javax.swing.JButton();
        MODIFICAR = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        numPagModificar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        isbnModificar = new javax.swing.JTextField();
        tituloModificar = new javax.swing.JTextField();
        categoriaModificar = new javax.swing.JTextField();
        precioModificar = new javax.swing.JTextField();
        modificarAccion = new javax.swing.JButton();
        atrasModificar = new javax.swing.JButton();
        buscarAccion1 = new javax.swing.JButton();
        ELIMINAR = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        numPagEliminar = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        isbnEliminar = new javax.swing.JTextField();
        tituloEliminar = new javax.swing.JTextField();
        categoriaEliminar = new javax.swing.JTextField();
        precioEliminar = new javax.swing.JTextField();
        eliminarAccion = new javax.swing.JButton();
        atrasEliminar = new javax.swing.JButton();
        ELECCION = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        añadir = new javax.swing.JButton();
        leer = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        eliminarCheck = new javax.swing.JCheckBox();
        leerCompleto = new javax.swing.JButton();
        atrasSeleccion = new javax.swing.JButton();
        añadir1 = new javax.swing.JButton();
        tipoEnciclopedia = new javax.swing.JRadioButton();
        tipoLibro = new javax.swing.JRadioButton();
        LEERCOMPLETO = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        atrasLecturaCompleta = new javax.swing.JButton();
        leerTodo = new javax.swing.JButton();
        tipoLibros = new javax.swing.ButtonGroup();
        reproductor = new javax.swing.JDialog();
        jComboBox1 = new javax.swing.JComboBox<>();
        stop = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        play = new javax.swing.JButton();
        reproducirSiguiente = new javax.swing.JButton();
        reproducirAnterior = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        INSERTAR.setMinimumSize(new java.awt.Dimension(319, 536));
        INSERTAR.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("NUMERO PAGINAS");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setOpaque(true);
        INSERTAR.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        numPagInsertar.setBackground(new java.awt.Color(225, 225, 225));
        numPagInsertar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        INSERTAR.getContentPane().add(numPagInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 280, 46));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("ISBN");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel8.setOpaque(true);
        INSERTAR.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("TITULO");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel9.setOpaque(true);
        INSERTAR.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("CATEGORIA");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel10.setOpaque(true);
        INSERTAR.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 70, -1));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("PRECIO");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel11.setOpaque(true);
        INSERTAR.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        isbnInsertar.setBackground(new java.awt.Color(225, 225, 225));
        isbnInsertar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        isbnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnInsertarActionPerformed(evt);
            }
        });
        INSERTAR.getContentPane().add(isbnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 46));

        tituloInsertar.setBackground(new java.awt.Color(225, 225, 225));
        tituloInsertar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        INSERTAR.getContentPane().add(tituloInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 280, 46));

        categoriaInsertar.setBackground(new java.awt.Color(225, 225, 225));
        categoriaInsertar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        INSERTAR.getContentPane().add(categoriaInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 280, 46));

        precioInsertar.setBackground(new java.awt.Color(225, 225, 225));
        precioInsertar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        INSERTAR.getContentPane().add(precioInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 280, 46));

        insertarAccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        insertarAccion.setText("INSERTAR DATOS");
        insertarAccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        insertarAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarAccionActionPerformed(evt);
            }
        });
        INSERTAR.getContentPane().add(insertarAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 180, 40));

        atrasAnadir.setText("Atras");
        atrasAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasAnadirActionPerformed(evt);
            }
        });
        INSERTAR.getContentPane().add(atrasAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        LEER.setMinimumSize(new java.awt.Dimension(319, 536));
        LEER.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("NUMERO PAGINAS");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setOpaque(true);
        LEER.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        numPagLeer.setBackground(new java.awt.Color(225, 225, 225));
        numPagLeer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LEER.getContentPane().add(numPagLeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 280, 46));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("ISBN");
        jLabel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel12.setOpaque(true);
        LEER.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("TITULO");
        jLabel13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel13.setOpaque(true);
        LEER.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("CATEGORIA");
        jLabel14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel14.setOpaque(true);
        LEER.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 70, -1));

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("PRECIO");
        jLabel15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel15.setOpaque(true);
        LEER.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        isbnLeer.setBackground(new java.awt.Color(225, 225, 225));
        isbnLeer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        isbnLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnLeerActionPerformed(evt);
            }
        });
        LEER.getContentPane().add(isbnLeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 46));

        tituloLeer.setBackground(new java.awt.Color(225, 225, 225));
        tituloLeer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LEER.getContentPane().add(tituloLeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 280, 46));

        categoriaLeer.setBackground(new java.awt.Color(225, 225, 225));
        categoriaLeer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LEER.getContentPane().add(categoriaLeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 280, 46));

        precioLeer.setBackground(new java.awt.Color(225, 225, 225));
        precioLeer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LEER.getContentPane().add(precioLeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 280, 46));

        leerAccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        leerAccion.setText("LEER DATOS");
        leerAccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        leerAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerAccionActionPerformed(evt);
            }
        });
        LEER.getContentPane().add(leerAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 180, 40));

        atrasLeer.setText("Atras");
        atrasLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasLeerActionPerformed(evt);
            }
        });
        LEER.getContentPane().add(atrasLeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        MODIFICAR.setMinimumSize(new java.awt.Dimension(319, 584));
        MODIFICAR.setResizable(false);
        MODIFICAR.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("NUMERO PAGINAS");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setOpaque(true);
        MODIFICAR.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        numPagModificar.setBackground(new java.awt.Color(225, 225, 225));
        numPagModificar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MODIFICAR.getContentPane().add(numPagModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 280, 46));

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("ISBN");
        jLabel16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel16.setOpaque(true);
        MODIFICAR.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("TITULO");
        jLabel17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel17.setOpaque(true);
        MODIFICAR.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("CATEGORIA");
        jLabel18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel18.setOpaque(true);
        MODIFICAR.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 70, -1));

        jLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("PRECIO");
        jLabel19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel19.setOpaque(true);
        MODIFICAR.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        isbnModificar.setBackground(new java.awt.Color(225, 225, 225));
        isbnModificar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        isbnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnModificarActionPerformed(evt);
            }
        });
        MODIFICAR.getContentPane().add(isbnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 46));

        tituloModificar.setBackground(new java.awt.Color(225, 225, 225));
        tituloModificar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tituloModificar.setOpaque(true);
        MODIFICAR.getContentPane().add(tituloModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 280, 46));

        categoriaModificar.setBackground(new java.awt.Color(225, 225, 225));
        categoriaModificar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MODIFICAR.getContentPane().add(categoriaModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 280, 46));

        precioModificar.setBackground(new java.awt.Color(225, 225, 225));
        precioModificar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MODIFICAR.getContentPane().add(precioModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 280, 46));

        modificarAccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        modificarAccion.setText("MODICAR");
        modificarAccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarAccionActionPerformed(evt);
            }
        });
        MODIFICAR.getContentPane().add(modificarAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 180, 40));

        atrasModificar.setText("Atras");
        atrasModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasModificarActionPerformed(evt);
            }
        });
        MODIFICAR.getContentPane().add(atrasModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        buscarAccion1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buscarAccion1.setText("BUSCAR");
        buscarAccion1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarAccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarAccion1ActionPerformed(evt);
            }
        });
        MODIFICAR.getContentPane().add(buscarAccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 180, 40));

        ELIMINAR.setMinimumSize(new java.awt.Dimension(319, 536));
        ELIMINAR.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("NUMERO PAGINAS");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.setOpaque(true);
        ELIMINAR.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        numPagEliminar.setBackground(new java.awt.Color(225, 225, 225));
        numPagEliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ELIMINAR.getContentPane().add(numPagEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 280, 46));

        jLabel20.setBackground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("ISBN");
        jLabel20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel20.setOpaque(true);
        ELIMINAR.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel21.setBackground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("TITULO");
        jLabel21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel21.setOpaque(true);
        ELIMINAR.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("CATEGORIA");
        jLabel22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel22.setOpaque(true);
        ELIMINAR.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 70, -1));

        jLabel23.setBackground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("PRECIO");
        jLabel23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel23.setOpaque(true);
        ELIMINAR.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        isbnEliminar.setBackground(new java.awt.Color(225, 225, 225));
        isbnEliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ELIMINAR.getContentPane().add(isbnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 46));

        tituloEliminar.setBackground(new java.awt.Color(225, 225, 225));
        tituloEliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ELIMINAR.getContentPane().add(tituloEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 280, 46));

        categoriaEliminar.setBackground(new java.awt.Color(225, 225, 225));
        categoriaEliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ELIMINAR.getContentPane().add(categoriaEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 280, 46));

        precioEliminar.setBackground(new java.awt.Color(225, 225, 225));
        precioEliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ELIMINAR.getContentPane().add(precioEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 280, 46));

        eliminarAccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminarAccion.setText("ELIMINAR");
        eliminarAccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarAccionActionPerformed(evt);
            }
        });
        ELIMINAR.getContentPane().add(eliminarAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 180, 40));

        atrasEliminar.setText("Atras");
        atrasEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasEliminarActionPerformed(evt);
            }
        });
        ELIMINAR.getContentPane().add(atrasEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        ELECCION.setMinimumSize(new java.awt.Dimension(642, 393));
        ELECCION.setResizable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 48)); // NOI18N
        jLabel2.setText("¿QUE QUIERES HACER?");
        jLabel2.setAutoscrolls(true);
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "BASES DE DATOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        añadir.setText("AÑADIR");
        añadir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirActionPerformed(evt);
            }
        });

        leer.setText("LEER");
        leer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        leer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerActionPerformed(evt);
            }
        });

        eliminar.setForeground(new java.awt.Color(255, 0, 0));
        eliminar.setText("ELEMINAR");
        eliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        modificar.setText("MODIFCAR");
        modificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        eliminarCheck.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        eliminarCheck.setText("Estoy seguro de mi elección");
        eliminarCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCheckActionPerformed(evt);
            }
        });

        leerCompleto.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        leerCompleto.setText("LECTURA COMPLETA");
        leerCompleto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        leerCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerCompletoActionPerformed(evt);
            }
        });

        atrasSeleccion.setText("Atras");
        atrasSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasSeleccionActionPerformed(evt);
            }
        });

        añadir1.setText("MEDIA");
        añadir1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        añadir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadir1ActionPerformed(evt);
            }
        });

        tipoEnciclopedia.setText("Enciclopedia");
        tipoEnciclopedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoEnciclopediaActionPerformed(evt);
            }
        });

        tipoLibro.setText("Libro");
        tipoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ELECCIONLayout = new javax.swing.GroupLayout(ELECCION.getContentPane());
        ELECCION.getContentPane().setLayout(ELECCIONLayout);
        ELECCIONLayout.setHorizontalGroup(
            ELECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ELECCIONLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(ELECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ELECCIONLayout.createSequentialGroup()
                        .addComponent(leer, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(leerCompleto))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ELECCIONLayout.createSequentialGroup()
                        .addGroup(ELECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ELECCIONLayout.createSequentialGroup()
                                .addComponent(tipoLibro)
                                .addGap(37, 37, 37)
                                .addComponent(tipoEnciclopedia))
                            .addGroup(ELECCIONLayout.createSequentialGroup()
                                .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(eliminarCheck)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ELECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(añadir1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atrasSeleccion))
                        .addGap(6, 6, 6)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        ELECCIONLayout.setVerticalGroup(
            ELECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ELECCIONLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ELECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(añadir1)
                    .addComponent(tipoEnciclopedia)
                    .addComponent(tipoLibro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(añadir)
                .addGap(18, 18, 18)
                .addGroup(ELECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leer)
                    .addComponent(leerCompleto))
                .addGap(18, 18, 18)
                .addComponent(modificar)
                .addGap(18, 18, 18)
                .addGroup(ELECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminar)
                    .addComponent(eliminarCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atrasSeleccion)
                .addGap(14, 14, 14))
        );

        LEERCOMPLETO.setMinimumSize(new java.awt.Dimension(692, 645));
        LEERCOMPLETO.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 3, 48)); // NOI18N
        jLabel7.setText("LECTURA DE LIBROS");
        jLabel7.setAutoscrolls(true);
        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "BASES DE DATOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        LEERCOMPLETO.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 42, -1, 98));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ISBN", "TITULO", "CATEGORIA", "PRECIO", "Nº PAGS", "TIPO"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        LEERCOMPLETO.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 146, 490, 440));

        atrasLecturaCompleta.setText("Atras");
        atrasLecturaCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasLecturaCompletaActionPerformed(evt);
            }
        });
        LEERCOMPLETO.getContentPane().add(atrasLecturaCompleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        leerTodo.setText("Leer");
        leerTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerTodoActionPerformed(evt);
            }
        });
        LEERCOMPLETO.getContentPane().add(leerTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 600, -1, -1));

        reproductor.setMinimumSize(new java.awt.Dimension(992, 599));
        reproductor.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cancion1", "cancion2", "cancion3", " ", " " }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox1MousePressed(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        reproductor.getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 90, -1));

        stop.setText("stop");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        reproductor.getContentPane().add(stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        pause.setText("pause");
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });
        reproductor.getContentPane().add(pause, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        play.setText("play");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        reproductor.getContentPane().add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        reproducirSiguiente.setText("siguiente");
        reproducirSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reproducirSiguienteActionPerformed(evt);
            }
        });
        reproductor.getContentPane().add(reproducirSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        reproducirAnterior.setText("anterior");
        reproducirAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reproducirAnteriorActionPerformed(evt);
            }
        });
        reproductor.getContentPane().add(reproducirAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jButton2.setText("atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        reproductor.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 19, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "peli1", "peli2", "peli3" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 248, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        reproductor.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 320, 310));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        reproductor.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 340, 290));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(584, 362));
        setPreferredSize(new java.awt.Dimension(584, 362));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel1.setText("CRUD BIBLIOTECA");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ANDREI ADELIN TOMA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 510, 80));

        jButton1.setText("EMPEZAR");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 140, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertarAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarAccionActionPerformed
        /*No es necesario, pero por legibilidad vamos declar variables de las caracteristicas del libro*/
        
        

        String ISBN = (isbnInsertar.getText());
        String TITULO = tituloInsertar.getText();
        String CATEGORIA = categoriaInsertar.getText();
        double PRECIO = Double.parseDouble(precioInsertar.getText());
        int NUMPAG = Integer.parseInt(numPagInsertar.getText());

        /*aqui aplicamos las variables a Libro*/
        
        libros.setIsbn(ISBN);
        libros.setTitulo(TITULO);
        libros.setCategoria(CATEGORIA);
        libros.setPrecio(PRECIO);
        libros.setNumPaginas(NUMPAG);
        if (gestor.agregarLibro(libros) == false) {
            JOptionPane.showMessageDialog(null, "error", "error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "ingresado", "ingresado", JOptionPane.INFORMATION_MESSAGE);
        }
        isbnInsertar.setText("");
        tituloInsertar.setText("");
        categoriaInsertar.setText("");
        precioInsertar.setText("");
        numPagInsertar.setText("");


    }//GEN-LAST:event_insertarAccionActionPerformed

    private void leerAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerAccionActionPerformed
        String ISBN = (isbnLeer.getText());
        if (gestor.buscarPorIsbn(ISBN) == null) {
            JOptionPane.showMessageDialog(null, "error", "error", JOptionPane.ERROR_MESSAGE);
        } else {
            libros = gestor.buscarPorIsbn(ISBN);
            isbnLeer.setText(libros.getIsbn());
            tituloLeer.setText(libros.getTitulo());
            categoriaLeer.setText(libros.getCategoria());
            precioLeer.setText(String.valueOf(libros.getPrecio()));
            numPagLeer.setText(String.valueOf(libros.getNumPaginas()));
        }
    }//GEN-LAST:event_leerAccionActionPerformed

    private void modificarAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarAccionActionPerformed
        // TODO add your handling code here:
        gestor.eliminarLibro(libros.getIsbn());

        String ISBN = (isbnModificar.getText());
        String TITULO = tituloModificar.getText();
        String CATEGORIA = categoriaModificar.getText();
        double PRECIO = Double.parseDouble(precioModificar.getText());
        int NUMPAG = Integer.parseInt(numPagModificar.getText());

        libros.setIsbn(ISBN);
        libros.setTitulo(TITULO);
        libros.setCategoria(CATEGORIA);
        libros.setPrecio(PRECIO);
        libros.setNumPaginas(NUMPAG);

        if (gestor.agregarLibro(libros) == false) {
            JOptionPane.showMessageDialog(null, "error", "2", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "ingresado", "ingresado", JOptionPane.INFORMATION_MESSAGE);
        }

        gestor.agregarLibro(libros);

    }//GEN-LAST:event_modificarAccionActionPerformed

    private void eliminarAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarAccionActionPerformed
        // TODO add your handling code here:
        String ISBN = (isbnEliminar.getText());
        if (gestor.eliminarLibro(ISBN) == true) {
            JOptionPane.showMessageDialog(null, "eliminado", "eliminado", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "error", "error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_eliminarAccionActionPerformed

    private void eliminarCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarCheckActionPerformed

    private void leerCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerCompletoActionPerformed
        // TODO add your handling code here:
        LEERCOMPLETO.setVisible(true);
        ELECCION.setVisible(false);

    }//GEN-LAST:event_leerCompletoActionPerformed

    private void atrasSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasSeleccionActionPerformed
        // TODO add your handling code here:
        ELECCION.setVisible(false);
        this.setVisible(true);

    }//GEN-LAST:event_atrasSeleccionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ELECCION.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void atrasLecturaCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasLecturaCompletaActionPerformed
        // TODO add your handling code here:
        ELECCION.setVisible(true);
        LEERCOMPLETO.setVisible(false);
    }//GEN-LAST:event_atrasLecturaCompletaActionPerformed

    private void añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirActionPerformed
        // TODO add your handling code here:
        INSERTAR.setVisible(true);
        ELECCION.setVisible(false);
    }//GEN-LAST:event_añadirActionPerformed

    private void leerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerActionPerformed
        // TODO add your handling code here:
        LEER.setVisible(true);
        ELECCION.setVisible(false);
    }//GEN-LAST:event_leerActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        MODIFICAR.setVisible(true);
        ELECCION.setVisible(false);
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        if (eliminarCheck.isSelected()) {
            ELIMINAR.setVisible(true);
            ELECCION.setVisible(false);
        }

    }//GEN-LAST:event_eliminarActionPerformed

    private void atrasAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasAnadirActionPerformed
        // TODO add your handling code here:
        ELECCION.setVisible(true);
        INSERTAR.setVisible(false);
    }//GEN-LAST:event_atrasAnadirActionPerformed

    private void atrasLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasLeerActionPerformed
        // TODO add your handlingfalse code here:
        ELECCION.setVisible(true);
        LEER.setVisible(false);
    }//GEN-LAST:event_atrasLeerActionPerformed

    private void atrasModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasModificarActionPerformed
        // TODO add your handling code here:
        ELECCION.setVisible(true);
        MODIFICAR.setVisible(false);
    }//GEN-LAST:event_atrasModificarActionPerformed

    private void atrasEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasEliminarActionPerformed
        // TODO add your handling code here:
        ELECCION.setVisible(true);
        ELIMINAR.setVisible(false);
    }//GEN-LAST:event_atrasEliminarActionPerformed


    private void leerTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerTodoActionPerformed

        // Limpiar la tabla antes de agregar nuevos datos
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        try {
            FileInputStream fis = new FileInputStream("biblioteca.dat");
            ObjectInputStream ois = new ObjectInputStream(fis);

            ArrayList<Libro> libros = (ArrayList<Libro>) ois.readObject();
            for (Libro libro : libros) {
                model.addRow(new Object[]{libro.getIsbn(), libro.getTitulo(), libro.getCategoria(), libro.getPrecio(), libro.getNumPaginas()});
            }

            ois.close();
            fis.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_leerTodoActionPerformed

    private void isbnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnInsertarActionPerformed

    private void isbnLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnLeerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnLeerActionPerformed

    private void isbnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnModificarActionPerformed

    private void buscarAccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarAccion1ActionPerformed
        // TODO add your handling code here:

        if (isbnModificar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "error", "error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String isbn = isbnModificar.getText();

        if (gestor.buscarPorIsbn(isbn) != null) {
            libros = gestor.buscarPorIsbn(isbn);
            JOptionPane.showMessageDialog(null, "buscado correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "error", "error", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_buscarAccion1ActionPerformed


    private void añadir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadir1ActionPerformed
        // TODO add your handling code here:
        reproductor.setVisible(true);
        ELECCION.setVisible(false);
    }//GEN-LAST:event_añadir1ActionPerformed

    private void tipoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoLibroActionPerformed

    private void tipoEnciclopediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoEnciclopediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoEnciclopediaActionPerformed

    private void reproducirAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproducirAnteriorActionPerformed
        // TODO add your handling code here:
        int posicion = jComboBox1.getSelectedIndex();
        if (jComboBox1.getSelectedIndex()<1) {
            posicion = 3;
        }
        jComboBox1.setSelectedIndex(posicion-1);
        String cancionSeleccionada = String.valueOf(jComboBox1.getSelectedItem());
    
    // Verificar y reproducir la canción
    initializeMediaPlayer(cancionSeleccionada);
    }//GEN-LAST:event_reproducirAnteriorActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        // TODO add your handling code here:
        if (mediaPlayer != null) {
            mediaPlayer.play();
        }

    }//GEN-LAST:event_playActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        // TODO add your handling code here:
        if (mediaPlayer != null) {
            mediaPlayer.stop();
        }
    }//GEN-LAST:event_stopActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        // TODO add your handling code here:
        if (mediaPlayer != null) {
            mediaPlayer.pause();
        }
    }//GEN-LAST:event_pauseActionPerformed

    private void reproducirSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproducirSiguienteActionPerformed
        // TODO add your handling code here:
        
        int posicion = jComboBox1.getSelectedIndex();
        if (jComboBox1.getSelectedIndex()>1) {
            posicion = -1;
        }
        jComboBox1.setSelectedIndex(posicion+1);
        String cancionSeleccionada = String.valueOf(jComboBox1.getSelectedItem());
    
    // Verificar y reproducir la canción
    initializeMediaPlayer(cancionSeleccionada);
    }//GEN-LAST:event_reproducirSiguienteActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ELECCION.setVisible(true);
        reproductor.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1MousePressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
            // Obtener la canción seleccionada
    String cancionSeleccionada = String.valueOf(jComboBox1.getSelectedItem());
    
    // Verificar y reproducir la canción
    initializeMediaPlayer(cancionSeleccionada);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox2ActionPerformed
    private MediaPlayer mediaPlayer;

    private void initializeMediaPlayer(String filePath) {
        try {
            if (mediaPlayer != null) {
                mediaPlayer.stop();
            }
            Media media = new Media(new File(filePath+".mp3").toURI().toString());
            mediaPlayer = new MediaPlayer(media);
            mediaPlayer.play();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error loading media: " + e.getMessage(),
                    "Media Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ELECCION;
    private javax.swing.JDialog ELIMINAR;
    private javax.swing.JDialog INSERTAR;
    private javax.swing.JDialog LEER;
    private javax.swing.JDialog LEERCOMPLETO;
    private javax.swing.JDialog MODIFICAR;
    private javax.swing.JButton atrasAnadir;
    private javax.swing.JButton atrasEliminar;
    private javax.swing.JButton atrasLecturaCompleta;
    private javax.swing.JButton atrasLeer;
    private javax.swing.JButton atrasModificar;
    private javax.swing.JButton atrasSeleccion;
    private javax.swing.JButton añadir;
    private javax.swing.JButton añadir1;
    private javax.swing.JButton buscarAccion1;
    private javax.swing.JTextField categoriaEliminar;
    private javax.swing.JTextField categoriaInsertar;
    private javax.swing.JTextField categoriaLeer;
    private javax.swing.JTextField categoriaModificar;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton eliminarAccion;
    private javax.swing.JCheckBox eliminarCheck;
    private javax.swing.JButton insertarAccion;
    private javax.swing.JTextField isbnEliminar;
    private javax.swing.JTextField isbnInsertar;
    private javax.swing.JTextField isbnLeer;
    private javax.swing.JTextField isbnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton leer;
    private javax.swing.JButton leerAccion;
    private javax.swing.JButton leerCompleto;
    private javax.swing.JButton leerTodo;
    private javax.swing.JButton modificar;
    private javax.swing.JButton modificarAccion;
    private javax.swing.JTextField numPagEliminar;
    private javax.swing.JTextField numPagInsertar;
    private javax.swing.JTextField numPagLeer;
    private javax.swing.JTextField numPagModificar;
    private javax.swing.JButton pause;
    private javax.swing.JButton play;
    private javax.swing.JTextField precioEliminar;
    private javax.swing.JTextField precioInsertar;
    private javax.swing.JTextField precioLeer;
    private javax.swing.JTextField precioModificar;
    private javax.swing.JButton reproducirAnterior;
    private javax.swing.JButton reproducirSiguiente;
    private javax.swing.JDialog reproductor;
    private javax.swing.JButton stop;
    private javax.swing.JRadioButton tipoEnciclopedia;
    private javax.swing.JRadioButton tipoLibro;
    private javax.swing.ButtonGroup tipoLibros;
    private javax.swing.JTextField tituloEliminar;
    private javax.swing.JTextField tituloInsertar;
    private javax.swing.JTextField tituloLeer;
    private javax.swing.JTextField tituloModificar;
    // End of variables declaration//GEN-END:variables
}
