/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crudbiblioteca;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tomaa
 */
public class UI extends javax.swing.JFrame {


    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        INSERTAR = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        numPagInsertar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        isbnInsertar = new javax.swing.JTextField();
        tituloInsertar = new javax.swing.JTextField();
        categoriaInsertar = new javax.swing.JTextField();
        precioInsertar = new javax.swing.JTextField();
        insertarAccion = new javax.swing.JButton();
        atrasAnadir = new javax.swing.JButton();
        LEER = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        numPagLeer = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        isbnLeer = new javax.swing.JTextField();
        tituloLeer = new javax.swing.JTextField();
        categoriaLeer = new javax.swing.JTextField();
        precioLeer = new javax.swing.JTextField();
        leerAccion = new javax.swing.JButton();
        atrasLeer = new javax.swing.JButton();
        MODIFICAR = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        atrasModificar = new javax.swing.JButton();
        ELIMINAR = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        atrasEliminar = new javax.swing.JButton();
        ELECCION = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        añadir = new javax.swing.JButton();
        leer = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        eliminarCheck = new javax.swing.JCheckBox();
        leerCompleto = new javax.swing.JButton();
        atrasSeleccion = new javax.swing.JButton();
        LEERCOMPLETO = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        atrasLecturaCompleta = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        INSERTAR.setMinimumSize(new java.awt.Dimension(319, 536));
        INSERTAR.setPreferredSize(new java.awt.Dimension(319, 536));
        INSERTAR.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("NUMERO PAGINAS");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setOpaque(true);
        INSERTAR.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        numPagInsertar.setBackground(new java.awt.Color(225, 225, 225));
        numPagInsertar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        INSERTAR.getContentPane().add(numPagInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 280, 46));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("ISBN");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel8.setOpaque(true);
        INSERTAR.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("TITULO");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel9.setOpaque(true);
        INSERTAR.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("CATEGORIA");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel10.setOpaque(true);
        INSERTAR.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 70, -1));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("PRECIO");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel11.setOpaque(true);
        INSERTAR.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        isbnInsertar.setBackground(new java.awt.Color(225, 225, 225));
        isbnInsertar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        isbnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnInsertarActionPerformed(evt);
            }
        });
        INSERTAR.getContentPane().add(isbnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 46));

        tituloInsertar.setBackground(new java.awt.Color(225, 225, 225));
        tituloInsertar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        INSERTAR.getContentPane().add(tituloInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 280, 46));

        categoriaInsertar.setBackground(new java.awt.Color(225, 225, 225));
        categoriaInsertar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        INSERTAR.getContentPane().add(categoriaInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 280, 46));

        precioInsertar.setBackground(new java.awt.Color(225, 225, 225));
        precioInsertar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        INSERTAR.getContentPane().add(precioInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 280, 46));

        insertarAccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        insertarAccion.setText("INSERTAR DATOS");
        insertarAccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        insertarAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarAccionActionPerformed(evt);
            }
        });
        INSERTAR.getContentPane().add(insertarAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 180, 40));

        atrasAnadir.setText("Atras");
        atrasAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasAnadirActionPerformed(evt);
            }
        });
        INSERTAR.getContentPane().add(atrasAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        LEER.setMinimumSize(new java.awt.Dimension(319, 536));
        LEER.setPreferredSize(new java.awt.Dimension(319, 536));
        LEER.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("NUMERO PAGINAS");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setOpaque(true);
        LEER.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        numPagLeer.setBackground(new java.awt.Color(225, 225, 225));
        numPagLeer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LEER.getContentPane().add(numPagLeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 280, 46));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("ISBN");
        jLabel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel12.setOpaque(true);
        LEER.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("TITULO");
        jLabel13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel13.setOpaque(true);
        LEER.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("CATEGORIA");
        jLabel14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel14.setOpaque(true);
        LEER.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 70, -1));

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("PRECIO");
        jLabel15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel15.setOpaque(true);
        LEER.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        isbnLeer.setBackground(new java.awt.Color(225, 225, 225));
        isbnLeer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        isbnLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnLeerActionPerformed(evt);
            }
        });
        LEER.getContentPane().add(isbnLeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 46));

        tituloLeer.setBackground(new java.awt.Color(225, 225, 225));
        tituloLeer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LEER.getContentPane().add(tituloLeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 280, 46));

        categoriaLeer.setBackground(new java.awt.Color(225, 225, 225));
        categoriaLeer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LEER.getContentPane().add(categoriaLeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 280, 46));

        precioLeer.setBackground(new java.awt.Color(225, 225, 225));
        precioLeer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LEER.getContentPane().add(precioLeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 280, 46));

        leerAccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        leerAccion.setText("LEER DATOS");
        leerAccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        leerAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerAccionActionPerformed(evt);
            }
        });
        LEER.getContentPane().add(leerAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 180, 40));

        atrasLeer.setText("Atras");
        atrasLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasLeerActionPerformed(evt);
            }
        });
        LEER.getContentPane().add(atrasLeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        MODIFICAR.setMinimumSize(new java.awt.Dimension(319, 536));
        MODIFICAR.setPreferredSize(new java.awt.Dimension(319, 536));
        MODIFICAR.setResizable(false);
        MODIFICAR.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("NUMERO PAGINAS");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setOpaque(true);
        MODIFICAR.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jTextField11.setBackground(new java.awt.Color(225, 225, 225));
        jTextField11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MODIFICAR.getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 280, 46));

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("ISBN");
        jLabel16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel16.setOpaque(true);
        MODIFICAR.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("TITULO");
        jLabel17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel17.setOpaque(true);
        MODIFICAR.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("CATEGORIA");
        jLabel18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel18.setOpaque(true);
        MODIFICAR.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 70, -1));

        jLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("PRECIO");
        jLabel19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel19.setOpaque(true);
        MODIFICAR.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jTextField12.setBackground(new java.awt.Color(225, 225, 225));
        jTextField12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MODIFICAR.getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 46));

        jTextField13.setBackground(new java.awt.Color(225, 225, 225));
        jTextField13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MODIFICAR.getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 280, 46));

        jTextField14.setBackground(new java.awt.Color(225, 225, 225));
        jTextField14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MODIFICAR.getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 280, 46));

        jTextField15.setBackground(new java.awt.Color(225, 225, 225));
        jTextField15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MODIFICAR.getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 280, 46));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("MODICAR");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        MODIFICAR.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 180, 40));

        atrasModificar.setText("Atras");
        atrasModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasModificarActionPerformed(evt);
            }
        });
        MODIFICAR.getContentPane().add(atrasModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        ELIMINAR.setMinimumSize(new java.awt.Dimension(319, 536));
        ELIMINAR.setPreferredSize(new java.awt.Dimension(319, 536));
        ELIMINAR.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("NUMERO PAGINAS");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.setOpaque(true);
        ELIMINAR.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jTextField16.setBackground(new java.awt.Color(225, 225, 225));
        jTextField16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ELIMINAR.getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 280, 46));

        jLabel20.setBackground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("ISBN");
        jLabel20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel20.setOpaque(true);
        ELIMINAR.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel21.setBackground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("TITULO");
        jLabel21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel21.setOpaque(true);
        ELIMINAR.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("CATEGORIA");
        jLabel22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel22.setOpaque(true);
        ELIMINAR.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 70, -1));

        jLabel23.setBackground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("PRECIO");
        jLabel23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel23.setOpaque(true);
        ELIMINAR.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jTextField17.setBackground(new java.awt.Color(225, 225, 225));
        jTextField17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ELIMINAR.getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 46));

        jTextField18.setBackground(new java.awt.Color(225, 225, 225));
        jTextField18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ELIMINAR.getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 280, 46));

        jTextField19.setBackground(new java.awt.Color(225, 225, 225));
        jTextField19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ELIMINAR.getContentPane().add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 280, 46));

        jTextField20.setBackground(new java.awt.Color(225, 225, 225));
        jTextField20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ELIMINAR.getContentPane().add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 280, 46));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("MODICAR");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        ELIMINAR.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 180, 40));

        atrasEliminar.setText("Atras");
        atrasEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasEliminarActionPerformed(evt);
            }
        });
        ELIMINAR.getContentPane().add(atrasEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        ELECCION.setMaximumSize(new java.awt.Dimension(667, 369));
        ELECCION.setMinimumSize(new java.awt.Dimension(667, 369));
        ELECCION.setResizable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 48)); // NOI18N
        jLabel2.setText("¿QUE QUIERES HACER?");
        jLabel2.setAutoscrolls(true);
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "BASES DE DATOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        añadir.setText("AÑADIR");
        añadir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirActionPerformed(evt);
            }
        });

        leer.setText("LEER");
        leer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        leer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerActionPerformed(evt);
            }
        });

        eliminar.setForeground(new java.awt.Color(255, 0, 0));
        eliminar.setText("ELEMINAR");
        eliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        modificar.setText("MODIFCAR");
        modificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        eliminarCheck.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        eliminarCheck.setText("Estoy seguro de mi elección");
        eliminarCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCheckActionPerformed(evt);
            }
        });

        leerCompleto.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        leerCompleto.setText("LECTURA COMPLETA");
        leerCompleto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        leerCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerCompletoActionPerformed(evt);
            }
        });

        atrasSeleccion.setText("Atras");
        atrasSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasSeleccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ELECCIONLayout = new javax.swing.GroupLayout(ELECCION.getContentPane());
        ELECCION.getContentPane().setLayout(ELECCIONLayout);
        ELECCIONLayout.setHorizontalGroup(
            ELECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ELECCIONLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(ELECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ELECCIONLayout.createSequentialGroup()
                        .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarCheck))
                    .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ELECCIONLayout.createSequentialGroup()
                        .addComponent(leer, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(leerCompleto))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ELECCIONLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(atrasSeleccion)
                .addGap(31, 31, 31))
        );
        ELECCIONLayout.setVerticalGroup(
            ELECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ELECCIONLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(añadir)
                .addGap(18, 18, 18)
                .addGroup(ELECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leer)
                    .addComponent(leerCompleto))
                .addGap(18, 18, 18)
                .addComponent(modificar)
                .addGap(18, 18, 18)
                .addGroup(ELECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminar)
                    .addComponent(eliminarCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atrasSeleccion)
                .addGap(14, 14, 14))
        );

        LEERCOMPLETO.setMinimumSize(new java.awt.Dimension(692, 645));
        LEERCOMPLETO.setPreferredSize(new java.awt.Dimension(692, 645));
        LEERCOMPLETO.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 3, 48)); // NOI18N
        jLabel7.setText("LECTURA DE LIBROS");
        jLabel7.setAutoscrolls(true);
        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "BASES DE DATOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        LEERCOMPLETO.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 42, -1, 98));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ISBN", "TITULO", "CATEGORIA", "PRECIO", "Nº PAGS"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        LEERCOMPLETO.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 146, 490, 440));

        atrasLecturaCompleta.setText("Atras");
        atrasLecturaCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasLecturaCompletaActionPerformed(evt);
            }
        });
        LEERCOMPLETO.getContentPane().add(atrasLecturaCompleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        LEERCOMPLETO.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 600, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(584, 362));
        setPreferredSize(new java.awt.Dimension(584, 362));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel1.setText("CRUD BIBLIOTECA");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ANDREI ADELIN TOMA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 510, 80));

        jButton1.setText("EMPEZAR");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 140, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertarAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarAccionActionPerformed

    }//GEN-LAST:event_insertarAccionActionPerformed

    private void leerAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerAccionActionPerformed

    }//GEN-LAST:event_leerAccionActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void eliminarCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarCheckActionPerformed

    private void leerCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerCompletoActionPerformed
        // TODO add your handling code here:
        LEERCOMPLETO.setVisible(true);
        ELECCION.setVisible(false);
        
    }//GEN-LAST:event_leerCompletoActionPerformed

    private void atrasSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasSeleccionActionPerformed
        // TODO add your handling code here:
        ELECCION.setVisible(false);
        this.setVisible(true);
        
    }//GEN-LAST:event_atrasSeleccionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ELECCION.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void atrasLecturaCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasLecturaCompletaActionPerformed
        // TODO add your handling code here:
        ELECCION.setVisible(true);
        LEERCOMPLETO.setVisible(false);
    }//GEN-LAST:event_atrasLecturaCompletaActionPerformed

    private void añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirActionPerformed
        // TODO add your handling code here:
        INSERTAR.setVisible(true);
        ELECCION.setVisible(false);
    }//GEN-LAST:event_añadirActionPerformed

    private void leerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerActionPerformed
        // TODO add your handling code here:
        LEER.setVisible(true);
        ELECCION.setVisible(false);
    }//GEN-LAST:event_leerActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        MODIFICAR.setVisible(true);
        ELECCION.setVisible(false);
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        if (eliminarCheck.isSelected()) {
         ELIMINAR.setVisible(true);
        ELECCION.setVisible(false);   
        }
        
    }//GEN-LAST:event_eliminarActionPerformed

    private void atrasAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasAnadirActionPerformed
        // TODO add your handling code here:
        ELECCION.setVisible(true);
        INSERTAR.setVisible(false);
    }//GEN-LAST:event_atrasAnadirActionPerformed

    private void atrasLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasLeerActionPerformed
        // TODO add your handlingfalse code here:
        ELECCION.setVisible(true);
        LEER.setVisible(false);
    }//GEN-LAST:event_atrasLeerActionPerformed

    private void atrasModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasModificarActionPerformed
        // TODO add your handling code here:
        ELECCION.setVisible(true);
        MODIFICAR.setVisible(false);
    }//GEN-LAST:event_atrasModificarActionPerformed

    private void atrasEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasEliminarActionPerformed
        // TODO add your handling code here:
        ELECCION.setVisible(true);
        ELIMINAR.setVisible(false);
    }//GEN-LAST:event_atrasEliminarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

    }//GEN-LAST:event_jButton6ActionPerformed

    private void isbnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnInsertarActionPerformed

    private void isbnLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnLeerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnLeerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ELECCION;
    private javax.swing.JDialog ELIMINAR;
    private javax.swing.JDialog INSERTAR;
    private javax.swing.JDialog LEER;
    private javax.swing.JDialog LEERCOMPLETO;
    private javax.swing.JDialog MODIFICAR;
    private javax.swing.JButton atrasAnadir;
    private javax.swing.JButton atrasEliminar;
    private javax.swing.JButton atrasLecturaCompleta;
    private javax.swing.JButton atrasLeer;
    private javax.swing.JButton atrasModificar;
    private javax.swing.JButton atrasSeleccion;
    private javax.swing.JButton añadir;
    private javax.swing.JTextField categoriaInsertar;
    private javax.swing.JTextField categoriaLeer;
    private javax.swing.JButton eliminar;
    private javax.swing.JCheckBox eliminarCheck;
    private javax.swing.JButton insertarAccion;
    private javax.swing.JTextField isbnInsertar;
    private javax.swing.JTextField isbnLeer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JButton leer;
    private javax.swing.JButton leerAccion;
    private javax.swing.JButton leerCompleto;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField numPagInsertar;
    private javax.swing.JTextField numPagLeer;
    private javax.swing.JTextField precioInsertar;
    private javax.swing.JTextField precioLeer;
    private javax.swing.JTextField tituloInsertar;
    private javax.swing.JTextField tituloLeer;
    // End of variables declaration//GEN-END:variables
}
