/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juegodragonball_remade;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author tomaa
 */
public class JuegoDragonBall_RemadeUI extends javax.swing.JFrame {

    /**
     * Creates new form JuegoDragonBall_RemadeUI
     */
    public JuegoDragonBall_RemadeUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new javax.swing.JLabel();
        button2 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        label0 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        label2.setText("BOO");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, -1, 20));

        button2.setBackground(new java.awt.Color(255, 153, 153));
        button2.setText("CREAR");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, -1, -1));

        button1.setBackground(new java.awt.Color(204, 204, 0));
        button1.setText("CREAR");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\BOO-ezgif.com-resize.gif")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });
        jPanel5.add(jLabel7);

        jPanel9.setBackground(new java.awt.Color(153, 153, 0));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel9.add(jLabel8);

        jPanel5.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(153, 153, 0));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel10.add(jLabel9);

        jPanel11.setBackground(new java.awt.Color(153, 153, 0));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel11.add(jLabel10);

        jPanel10.add(jPanel11);

        jPanel5.add(jPanel10);

        jPanel12.setBackground(new java.awt.Color(153, 153, 0));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel12.add(jLabel11);

        jPanel13.setBackground(new java.awt.Color(153, 153, 0));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel13.add(jLabel12);

        jPanel12.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(153, 153, 0));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel14.add(jLabel13);

        jPanel15.setBackground(new java.awt.Color(153, 153, 0));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel15.add(jLabel14);

        jPanel14.add(jPanel15);

        jPanel12.add(jPanel14);

        jPanel16.setBackground(new java.awt.Color(153, 153, 0));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel16.add(jLabel15);

        jPanel17.setBackground(new java.awt.Color(153, 153, 0));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel17.add(jLabel16);

        jPanel16.add(jPanel17);

        jPanel18.setBackground(new java.awt.Color(153, 153, 0));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel18.add(jLabel17);

        jPanel19.setBackground(new java.awt.Color(153, 153, 0));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel19.add(jLabel18);

        jPanel18.add(jPanel19);

        jPanel16.add(jPanel18);

        jPanel20.setBackground(new java.awt.Color(153, 153, 0));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel20.add(jLabel19);

        jPanel21.setBackground(new java.awt.Color(153, 153, 0));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel21.add(jLabel20);

        jPanel20.add(jPanel21);

        jPanel22.setBackground(new java.awt.Color(153, 153, 0));

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel22.add(jLabel21);

        jPanel23.setBackground(new java.awt.Color(153, 153, 0));

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel23.add(jLabel22);

        jPanel22.add(jPanel23);

        jPanel20.add(jPanel22);

        jPanel16.add(jPanel20);

        jPanel12.add(jPanel16);

        jPanel5.add(jPanel12);

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 240, 310));

        jPanel24.setBackground(new java.awt.Color(153, 153, 0));

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel24.add(jLabel23);

        jPanel25.setBackground(new java.awt.Color(153, 153, 0));

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel25.add(jLabel24);

        jPanel24.add(jPanel25);

        jPanel26.setBackground(new java.awt.Color(153, 153, 0));

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel26.add(jLabel25);

        jPanel27.setBackground(new java.awt.Color(153, 153, 0));

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel27.add(jLabel26);

        jPanel26.add(jPanel27);

        jPanel24.add(jPanel26);

        jPanel28.setBackground(new java.awt.Color(153, 153, 0));

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel28.add(jLabel27);

        jPanel29.setBackground(new java.awt.Color(153, 153, 0));

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel29.add(jLabel28);

        jPanel28.add(jPanel29);

        jPanel30.setBackground(new java.awt.Color(153, 153, 0));

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel30.add(jLabel29);

        jPanel31.setBackground(new java.awt.Color(153, 153, 0));

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel31.add(jLabel30);

        jPanel30.add(jPanel31);

        jPanel28.add(jPanel30);

        jPanel32.setBackground(new java.awt.Color(153, 153, 0));

        jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel32.add(jLabel31);

        jPanel33.setBackground(new java.awt.Color(153, 153, 0));

        jLabel32.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel33.add(jLabel32);

        jPanel32.add(jPanel33);

        jPanel34.setBackground(new java.awt.Color(153, 153, 0));

        jLabel33.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel34.add(jLabel33);

        jPanel35.setBackground(new java.awt.Color(153, 153, 0));

        jLabel34.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel35.add(jLabel34);

        jPanel34.add(jPanel35);

        jPanel32.add(jPanel34);

        jPanel36.setBackground(new java.awt.Color(153, 153, 0));

        jLabel35.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel36.add(jLabel35);

        jPanel37.setBackground(new java.awt.Color(153, 153, 0));

        jLabel36.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel37.add(jLabel36);

        jPanel36.add(jPanel37);

        jPanel38.setBackground(new java.awt.Color(153, 153, 0));

        jLabel37.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel38.add(jLabel37);

        jPanel39.setBackground(new java.awt.Color(153, 153, 0));

        jLabel38.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\039f66bfd6b755978459b794b16ec58a186206c0_hq-ezgif.com-crop.gif")); // NOI18N
        jPanel39.add(jLabel38);

        jPanel38.add(jPanel39);

        jPanel36.add(jPanel38);

        jPanel32.add(jPanel36);

        jPanel28.add(jPanel32);

        jPanel24.add(jPanel28);

        getContentPane().add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 240, 310));

        label0.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 48)); // NOI18N
        label0.setText("JUEGAZO DRAGON BALL");
        getContentPane().add(label0, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 610, 90));

        label1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        label1.setText("NAMEKIANO");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 100, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        
        
        
        
        
    }//GEN-LAST:event_jLabel7MouseEntered

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Has seleccionado " +label1.getText().toLowerCase());
        
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Has seleccionado " + label2.getText().toLowerCase());
    }//GEN-LAST:event_button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoDragonBall_RemadeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoDragonBall_RemadeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoDragonBall_RemadeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoDragonBall_RemadeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoDragonBall_RemadeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel label0;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    // End of variables declaration//GEN-END:variables
}
