/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crud_barco;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tomaa
 */
public class UI extends javax.swing.JFrame {

   
    BarcoManager gestor = new BarcoManager();
     Barco barcos = new Barco();
     
    /**
     * Creates new form UI
     */
    public UI() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Insertar = new javax.swing.JDialog();
        matriculaInsertar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombreInsertar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        esloraInsertar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        añoInsertar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        insertarAccion = new javax.swing.JButton();
        atrasInsertar = new javax.swing.JButton();
        tipoInsertar = new javax.swing.JComboBox<>();
        Leer = new javax.swing.JDialog();
        matriculaLeer = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nombreLeer = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        esloraLeer = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        añoLeer = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        leerAccion = new javax.swing.JButton();
        atrasLeer = new javax.swing.JButton();
        tipoLeer = new javax.swing.JTextField();
        Modificar = new javax.swing.JDialog();
        matriculaModificar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        nombreModificar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        esloraModificar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        añoModificar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        modificarrAccion = new javax.swing.JButton();
        atrasModificar = new javax.swing.JButton();
        tipoModificar = new javax.swing.JComboBox<>();
        buscarAccion = new javax.swing.JButton();
        Eliminar = new javax.swing.JDialog();
        matriculaEliminar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        eliminarAccion = new javax.swing.JButton();
        atrasEliminar = new javax.swing.JButton();
        LeerCompleto = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        atrasTabla = new javax.swing.JButton();
        leerCompleto = new javax.swing.JButton();
        Selector = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        insertarInterfaz = new javax.swing.JToggleButton();
        leerInterfaz = new javax.swing.JToggleButton();
        leerTablaInterfaz = new javax.swing.JToggleButton();
        modificarInterfaz = new javax.swing.JToggleButton();
        eliminarInterfaz = new javax.swing.JToggleButton();
        atrasSelector = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comenzarInterfaz = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        Insertar.setMinimumSize(new java.awt.Dimension(400, 666));

        matriculaInsertar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        matriculaInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaInsertarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("MATRICULA");

        nombreInsertar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("NOMBRE");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("TIPO");

        esloraInsertar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("ESLORA");

        añoInsertar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        añoInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añoInsertarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("AÑO DE FABRICACIÓN");

        insertarAccion.setText("INSERTAR");
        insertarAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarAccionActionPerformed(evt);
            }
        });

        atrasInsertar.setText("Atras...");
        atrasInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasInsertarActionPerformed(evt);
            }
        });

        tipoInsertar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Velero", "Crucero", "Yate" }));

        javax.swing.GroupLayout InsertarLayout = new javax.swing.GroupLayout(Insertar.getContentPane());
        Insertar.getContentPane().setLayout(InsertarLayout);
        InsertarLayout.setHorizontalGroup(
            InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertarLayout.createSequentialGroup()
                .addGroup(InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsertarLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(añoInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(esloraInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(nombreInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(matriculaInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(InsertarLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(insertarAccion)))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsertarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(atrasInsertar)
                .addGap(14, 14, 14))
        );
        InsertarLayout.setVerticalGroup(
            InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atrasInsertar)
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matriculaInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(esloraInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(añoInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(insertarAccion)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        Leer.setMinimumSize(new java.awt.Dimension(400, 666));

        matriculaLeer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("MATRICULA");

        nombreLeer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("NOMBRE");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("TIPO");

        esloraLeer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("ESLORA");

        añoLeer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        añoLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añoLeerActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("AÑO DE FABRICACIÓN");

        leerAccion.setText("LEER");
        leerAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerAccionActionPerformed(evt);
            }
        });

        atrasLeer.setText("Atras...");
        atrasLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasLeerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeerLayout = new javax.swing.GroupLayout(Leer.getContentPane());
        Leer.getContentPane().setLayout(LeerLayout);
        LeerLayout.setHorizontalGroup(
            LeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeerLayout.createSequentialGroup()
                .addGroup(LeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeerLayout.createSequentialGroup()
                        .addGroup(LeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LeerLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(LeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11)
                                    .addComponent(añoLeer, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(jLabel10)
                                    .addComponent(esloraLeer, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(nombreLeer, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(jLabel7)
                                    .addComponent(matriculaLeer, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(tipoLeer)))
                            .addGroup(LeerLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(leerAccion)))
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(atrasLeer)))
                .addContainerGap())
        );
        LeerLayout.setVerticalGroup(
            LeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atrasLeer)
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matriculaLeer, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreLeer, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoLeer, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(esloraLeer, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(añoLeer, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(leerAccion)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        Modificar.setMinimumSize(new java.awt.Dimension(400, 666));

        matriculaModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("MATRICULA");

        nombreModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("NOMBRE");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("TIPO");

        esloraModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("ESLORA");

        añoModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        añoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añoModificarActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("AÑO DE FABRICACIÓN");

        modificarrAccion.setText("MODIFICAR");
        modificarrAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarrAccionActionPerformed(evt);
            }
        });

        atrasModificar.setText("Atras...");
        atrasModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasModificarActionPerformed(evt);
            }
        });

        tipoModificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Velero", "Crucero", "Yate" }));

        buscarAccion.setText("BUSCAR");
        buscarAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarAccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModificarLayout = new javax.swing.GroupLayout(Modificar.getContentPane());
        Modificar.getContentPane().setLayout(ModificarLayout);
        ModificarLayout.setHorizontalGroup(
            ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarLayout.createSequentialGroup()
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificarLayout.createSequentialGroup()
                        .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ModificarLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(añoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(esloraModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(nombreModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(matriculaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ModificarLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(modificarrAccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buscarAccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(atrasModificar)))
                .addContainerGap())
        );
        ModificarLayout.setVerticalGroup(
            ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atrasModificar)
                .addGap(40, 40, 40)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matriculaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(esloraModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(añoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(buscarAccion)
                .addGap(18, 18, 18)
                .addComponent(modificarrAccion)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        Eliminar.setMinimumSize(new java.awt.Dimension(400, 222));

        matriculaEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("MATRICULA");

        eliminarAccion.setText("INSERTAR");
        eliminarAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarAccionActionPerformed(evt);
            }
        });

        atrasEliminar.setText("Atras...");
        atrasEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EliminarLayout = new javax.swing.GroupLayout(Eliminar.getContentPane());
        Eliminar.getContentPane().setLayout(EliminarLayout);
        EliminarLayout.setHorizontalGroup(
            EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarLayout.createSequentialGroup()
                .addGroup(EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EliminarLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(matriculaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EliminarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(atrasEliminar)))
                .addContainerGap())
            .addGroup(EliminarLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(eliminarAccion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EliminarLayout.setVerticalGroup(
            EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atrasEliminar)
                .addGap(40, 40, 40)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matriculaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(eliminarAccion)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        LeerCompleto.setMinimumSize(new java.awt.Dimension(713, 599));
        LeerCompleto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MATRICULA", "NOMBRE", "TIPO", "ESLORA", "AÑO"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        LeerCompleto.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        atrasTabla.setText("Atras...");
        atrasTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasTablaActionPerformed(evt);
            }
        });
        LeerCompleto.getContentPane().add(atrasTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        leerCompleto.setText("jButton1");
        leerCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerCompletoActionPerformed(evt);
            }
        });
        LeerCompleto.getContentPane().add(leerCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, -1, -1));

        Selector.setMinimumSize(new java.awt.Dimension(551, 454));

        jLabel22.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel22.setText("¿QUE QUIERES HACER?");
        jLabel22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        insertarInterfaz.setText("INSERTAR");
        insertarInterfaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarInterfazActionPerformed(evt);
            }
        });

        leerInterfaz.setText("LEER");
        leerInterfaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerInterfazActionPerformed(evt);
            }
        });

        leerTablaInterfaz.setText("LEER TABLA");
        leerTablaInterfaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerTablaInterfazActionPerformed(evt);
            }
        });

        modificarInterfaz.setText("MODIFICAR");
        modificarInterfaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarInterfazActionPerformed(evt);
            }
        });

        eliminarInterfaz.setText("ELIMINAR");
        eliminarInterfaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarInterfazActionPerformed(evt);
            }
        });

        atrasSelector.setText("Atras");
        atrasSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasSelectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SelectorLayout = new javax.swing.GroupLayout(Selector.getContentPane());
        Selector.getContentPane().setLayout(SelectorLayout);
        SelectorLayout.setHorizontalGroup(
            SelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectorLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(SelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(modificarInterfaz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminarInterfaz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leerInterfaz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertarInterfaz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(leerTablaInterfaz)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectorLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(SelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectorLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectorLayout.createSequentialGroup()
                        .addComponent(atrasSelector)
                        .addGap(30, 30, 30))))
        );
        SelectorLayout.setVerticalGroup(
            SelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(atrasSelector)
                .addGap(98, 98, 98)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(insertarInterfaz, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leerInterfaz)
                    .addComponent(leerTablaInterfaz))
                .addGap(18, 18, 18)
                .addComponent(modificarInterfaz)
                .addGap(18, 18, 18)
                .addComponent(eliminarInterfaz)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(661, 442));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("BIENVENIDO A CRUD BARCOS");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        comenzarInterfaz.setText("COMENZAR");
        comenzarInterfaz.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        comenzarInterfaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarInterfazActionPerformed(evt);
            }
        });

        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(comenzarInterfaz)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(comenzarInterfaz)
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        /*Sirve para cuando le des el programa se cierre*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void añoInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añoInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añoInsertarActionPerformed

    private void insertarAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarAccionActionPerformed
        // TODO add your handling code here:
        /*Aqui estoy asignando valores a cada variable que se pide de los barcos*/
        /*Tambien estoy poniendo un par de condicionales; que los campos no esten vacios y que el esloran sea mayor o igual a 3*/
         Barco barcos2 = new Barco();
        
        String matricula = (matriculaInsertar.getText());
        String nombre = nombreInsertar.getText();
        String tipo =String.valueOf( tipoInsertar.getSelectedItem());
        
        int eslora = Integer.parseInt(esloraInsertar.getText());
        if (eslora <3) {
                        JOptionPane.showMessageDialog(null, "Esloran mayor a 3m", "error", JOptionPane.ERROR_MESSAGE);
return;
        }
        int año = Integer.parseInt(añoInsertar.getText());

        /*aqui aplicamos las variables a Libro*/
        
        barcos2.setMatrícula(matricula);
        barcos2.setNombre(nombre);
        barcos2.setTipo(tipo);
        barcos2.setEslora(eslora);
        barcos2.setAño(año);
        if (gestor.agregarBarco(barcos2) == false) {
            JOptionPane.showMessageDialog(null, "error", "error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "ingresado", "ingresado", JOptionPane.INFORMATION_MESSAGE);
        }
        matriculaInsertar.setText("");
        nombreInsertar.setText("");
        
        esloraInsertar.setText("");
        añoInsertar.setText("");



    }//GEN-LAST:event_insertarAccionActionPerformed

    private void añoLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añoLeerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añoLeerActionPerformed

    private void leerAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerAccionActionPerformed
        // TODO add your handling code here:
        /*Aqui llamamos al metodo que nos devuelve el barco que hemos pedido leer por Matricula*/
        String matricula = matriculaLeer.getText();
        if (gestor.buscarPorMatricula(matricula) == null) {
            JOptionPane.showMessageDialog(null, "Este barco no existe", "MATRICULA", JOptionPane.ERROR_MESSAGE);
            return;
        }
        /*La forma de mostrar los valores*/
        barcos = gestor.buscarPorMatricula(matricula);
        matriculaLeer.setText(barcos.getMatrícula());
        nombreLeer.setText(barcos.getNombre());
        tipoLeer.setText(barcos.getTipo());
        esloraLeer.setText(String.valueOf(barcos.getEslora()));
        añoLeer.setText(String.valueOf(barcos.getAño()));

    }//GEN-LAST:event_leerAccionActionPerformed

    private void añoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añoModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añoModificarActionPerformed

    private void modificarrAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarrAccionActionPerformed
        // TODO add your handling code here:
        /*Aqui he llamado a dos metodos, uno que elimina el que hemos buscado por matricula, y el otro añade el barco nuevo*/
        gestor.eliminarBarco(barcos.getMatrícula());

        String matricula = matriculaModificar.getText();
        String nombre = nombreModificar.getText();
        String tipo = String.valueOf(tipoModificar.getSelectedItem());
        int eslora = Integer.parseInt(esloraModificar.getText());
        int año = Integer.parseInt(añoModificar.getText());

        barcos.setMatrícula(matricula);
        barcos.setNombre(nombre);
        barcos.setTipo(tipo);
        barcos.setEslora(eslora);
        barcos.setAño(año);
        JOptionPane.showMessageDialog(null, "Creado con exito");
        gestor.agregarBarco(barcos);
        modificarrAccion.setVisible(false);
        buscarAccion.setVisible(true);

    }//GEN-LAST:event_modificarrAccionActionPerformed

    private void eliminarAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarAccionActionPerformed
        // TODO add your handling code here:
        /*Gracias a la matricula proporcionada, este eliminará el barco del archivo*/
        
        String matricula = matriculaEliminar.getText();
        if (gestor.eliminarBarco(matricula)==false) {
            JOptionPane.showMessageDialog(null, "Este barco no existe", "MATRICULA", JOptionPane.ERROR_MESSAGE);
        }else{
                    JOptionPane.showMessageDialog(null, "Eliminado con exito");

        }

    }//GEN-LAST:event_eliminarAccionActionPerformed

    private void matriculaInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculaInsertarActionPerformed

    private void leerInterfazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerInterfazActionPerformed
        // TODO add your handling code here:
        Leer.setVisible(true);
        Selector.setVisible(false);
    }//GEN-LAST:event_leerInterfazActionPerformed

    private void insertarInterfazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarInterfazActionPerformed
        // TODO add your handling code here:
        Insertar.setVisible(true);
        Selector.setVisible(false);
    }//GEN-LAST:event_insertarInterfazActionPerformed

    private void modificarInterfazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarInterfazActionPerformed
        // TODO add your handling code here:
        modificarrAccion.setVisible(false);
        Modificar.setVisible(true);
        Selector.setVisible(false);
    }//GEN-LAST:event_modificarInterfazActionPerformed

    private void eliminarInterfazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarInterfazActionPerformed
        // TODO add your handling code here:
        Eliminar.setVisible(true);
        Selector.setVisible(false);
    }//GEN-LAST:event_eliminarInterfazActionPerformed

    private void leerTablaInterfazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerTablaInterfazActionPerformed
        // TODO add your handling code here:
        LeerCompleto.setVisible(true);
        Selector.setVisible(false);
    }//GEN-LAST:event_leerTablaInterfazActionPerformed

    private void comenzarInterfazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarInterfazActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Selector.setVisible(true);
    }//GEN-LAST:event_comenzarInterfazActionPerformed

    private void atrasInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasInsertarActionPerformed
        // TODO add your handling code here:
        Insertar.setVisible(false);
        Selector.setVisible(true);
    }//GEN-LAST:event_atrasInsertarActionPerformed

    private void atrasLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasLeerActionPerformed
        // TODO add your handling code here:
        Leer.setVisible(false);
        Selector.setVisible(true);
    }//GEN-LAST:event_atrasLeerActionPerformed

    private void atrasModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasModificarActionPerformed
        // TODO add your handling code here:
        Modificar.setVisible(false);
        Selector.setVisible(true);
    }//GEN-LAST:event_atrasModificarActionPerformed

    private void atrasEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasEliminarActionPerformed
        // TODO add your handling code here:
        Eliminar.setVisible(false);
        Selector.setVisible(true);
    }//GEN-LAST:event_atrasEliminarActionPerformed

    private void atrasTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasTablaActionPerformed
        // TODO add your handling code here:
        LeerCompleto.setVisible(false);
        Selector.setVisible(true);
    }//GEN-LAST:event_atrasTablaActionPerformed

    private void buscarAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarAccionActionPerformed
        // TODO add your handling code here:
        /*Imprescindible para que la mdificacion funcione, primero se busca el libro a modifical, luego se guarda y proseguimos con el boton modificar*/
        String matricula = matriculaModificar.getText();
        
        if (gestor.buscarPorMatricula(matricula) == null) {
            JOptionPane.showMessageDialog(null, "Este barco no existe", "No existe", JOptionPane.ERROR_MESSAGE);
            return;
        }
        barcos = gestor.buscarPorMatricula(matricula);
        buscarAccion.setVisible(false);
        modificarrAccion.setVisible(true);

    }//GEN-LAST:event_buscarAccionActionPerformed

    private void atrasSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasSelectorActionPerformed
        // TODO add your handling code here:
        Selector.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_atrasSelectorActionPerformed

    private void leerCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerCompletoActionPerformed
        // TODO add your handling code here:
        // Limpiar la tabla antes de agregar nuevos datos
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        try {
            FileInputStream fis = new FileInputStream("barcos.dat");
            ObjectInputStream ois = new ObjectInputStream(fis);

            List<Barco> barcos1 = gestor.obtenerTodosLosBarcos();
            for (Barco barco : barcos1) {
                model.addRow(new Object[]{barco.getMatrícula(), barco.getNombre(), barco.getTipo(), barco.getEslora(), barco.getAño()});
            }

            ois.close();
            fis.close();
        } catch (IOException e) {

        }
    }//GEN-LAST:event_leerCompletoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Eliminar;
    private javax.swing.JDialog Insertar;
    private javax.swing.JDialog Leer;
    private javax.swing.JDialog LeerCompleto;
    private javax.swing.JDialog Modificar;
    private javax.swing.JDialog Selector;
    private javax.swing.JButton atrasEliminar;
    private javax.swing.JButton atrasInsertar;
    private javax.swing.JButton atrasLeer;
    private javax.swing.JButton atrasModificar;
    private javax.swing.JButton atrasSelector;
    private javax.swing.JButton atrasTabla;
    private javax.swing.JTextField añoInsertar;
    private javax.swing.JTextField añoLeer;
    private javax.swing.JTextField añoModificar;
    private javax.swing.JButton buscarAccion;
    private javax.swing.JButton comenzarInterfaz;
    private javax.swing.JButton eliminarAccion;
    private javax.swing.JToggleButton eliminarInterfaz;
    private javax.swing.JTextField esloraInsertar;
    private javax.swing.JTextField esloraLeer;
    private javax.swing.JTextField esloraModificar;
    private javax.swing.JButton insertarAccion;
    private javax.swing.JToggleButton insertarInterfaz;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton leerAccion;
    private javax.swing.JButton leerCompleto;
    private javax.swing.JToggleButton leerInterfaz;
    private javax.swing.JToggleButton leerTablaInterfaz;
    private javax.swing.JTextField matriculaEliminar;
    private javax.swing.JTextField matriculaInsertar;
    private javax.swing.JTextField matriculaLeer;
    private javax.swing.JTextField matriculaModificar;
    private javax.swing.JToggleButton modificarInterfaz;
    private javax.swing.JButton modificarrAccion;
    private javax.swing.JTextField nombreInsertar;
    private javax.swing.JTextField nombreLeer;
    private javax.swing.JTextField nombreModificar;
    private javax.swing.JComboBox<String> tipoInsertar;
    private javax.swing.JTextField tipoLeer;
    private javax.swing.JComboBox<String> tipoModificar;
    // End of variables declaration//GEN-END:variables
}
