/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermercado;

/**
 *
 * @author tomaa
 */
public class UI extends javax.swing.JFrame {
    
    /**
     * Creates new form UI
     */
movimiento mov1;

        movimiento mov2;

        movimiento mov3;

    public UI() {
        initComponents();
        mov1 = new movimiento(persona1, fin);

         mov2 = new movimiento(persona2, fin);

         mov3 = new movimiento(persona3, fin);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        persona3 = new javax.swing.JLabel();
        persona1 = new javax.swing.JLabel();
        persona2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tiempo1 = new javax.swing.JLabel();
        tiempo2 = new javax.swing.JLabel();
        tiempo3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        fin = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setOpaque(true);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 11, 342));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setOpaque(true);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 11, 342));

        persona3.setBackground(new java.awt.Color(0, 0, 0));
        persona3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        persona3.setForeground(new java.awt.Color(255, 255, 255));
        persona3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        persona3.setText("0");
        persona3.setOpaque(true);
        getContentPane().add(persona3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 90, 60));

        persona1.setBackground(new java.awt.Color(0, 0, 0));
        persona1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        persona1.setForeground(new java.awt.Color(255, 255, 255));
        persona1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        persona1.setText("0");
        persona1.setOpaque(true);
        getContentPane().add(persona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 90, 60));

        persona2.setBackground(new java.awt.Color(0, 0, 0));
        persona2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        persona2.setForeground(new java.awt.Color(255, 255, 255));
        persona2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        persona2.setText("0");
        persona2.setOpaque(true);
        getContentPane().add(persona2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 90, 60));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 90, -1));

        tiempo1.setText("0.0");
        getContentPane().add(tiempo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        tiempo2.setText("0.0");
        getContentPane().add(tiempo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        tiempo3.setText("0.0");
        getContentPane().add(tiempo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setOpaque(true);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 0, 650, 10));

        fin.setBackground(new java.awt.Color(0, 0, 0));
        fin.setText("jLabel1");
        fin.setOpaque(true);
        getContentPane().add(fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 640, -1));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, -1, -1));

        jButton3.setText("jButton3");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        persona1.setText(String.valueOf(mov1.numeroRandomEntero()));
        persona2.setText(String.valueOf(mov2.numeroRandomEntero()));
        persona3.setText(String.valueOf(mov3.numeroRandomEntero()));
        mov3.start();
        mov1.start();
        mov2.start();
        

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        tiempo1.setText(String.valueOf((double)mov1.gettiempoRequerido()/10));
        tiempo2.setText(String.valueOf((double)mov2.gettiempoRequerido()/10));
        tiempo3.setText(String.valueOf((double)mov3.gettiempoRequerido()/10));
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel persona1;
    private javax.swing.JLabel persona2;
    private javax.swing.JLabel persona3;
    private javax.swing.JLabel tiempo1;
    private javax.swing.JLabel tiempo2;
    private javax.swing.JLabel tiempo3;
    // End of variables declaration//GEN-END:variables
}
