/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package circuito;

/**
 *
 * @author tomaa
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mario = new javax.swing.JLabel();
        delim4 = new javax.swing.JLabel();
        delim2 = new javax.swing.JLabel();
        delim3 = new javax.swing.JLabel();
        delim5 = new javax.swing.JLabel();
        delim1 = new javax.swing.JLabel();
        delim7 = new javax.swing.JLabel();
        delim8 = new javax.swing.JLabel();
        delim6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mario.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\mario.png")); // NOI18N
        getContentPane().add(mario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        delim4.setBackground(new java.awt.Color(0, 0, 0));
        delim4.setText("jLabel2");
        delim4.setOpaque(true);
        getContentPane().add(delim4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 10, 20));

        delim2.setBackground(new java.awt.Color(0, 0, 0));
        delim2.setText("jLabel2");
        delim2.setOpaque(true);
        getContentPane().add(delim2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 10, 20));

        delim3.setBackground(new java.awt.Color(0, 0, 0));
        delim3.setText("jLabel2");
        delim3.setOpaque(true);
        getContentPane().add(delim3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 10, 20));

        delim5.setBackground(new java.awt.Color(0, 0, 0));
        delim5.setText("jLabel2");
        delim5.setOpaque(true);
        getContentPane().add(delim5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 10, 20));

        delim1.setBackground(new java.awt.Color(0, 0, 0));
        delim1.setText("jLabel2");
        delim1.setOpaque(true);
        getContentPane().add(delim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 10, 20));

        delim7.setBackground(new java.awt.Color(0, 0, 0));
        delim7.setText("jLabel2");
        delim7.setOpaque(true);
        getContentPane().add(delim7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 10, 20));

        delim8.setBackground(new java.awt.Color(0, 0, 0));
        delim8.setText("jLabel2");
        delim8.setOpaque(true);
        getContentPane().add(delim8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 10, 20));

        delim6.setBackground(new java.awt.Color(0, 0, 0));
        delim6.setText("jLabel2");
        delim6.setOpaque(true);
        getContentPane().add(delim6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 10, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\circuito(1).png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 451, 324));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Carrera race = new Carrera(mario, delim1,delim2,delim3,delim4,delim5,delim6,delim7,delim8);
        race.start();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel delim1;
    private javax.swing.JLabel delim2;
    private javax.swing.JLabel delim3;
    private javax.swing.JLabel delim4;
    private javax.swing.JLabel delim5;
    private javax.swing.JLabel delim6;
    private javax.swing.JLabel delim7;
    private javax.swing.JLabel delim8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mario;
    // End of variables declaration//GEN-END:variables
}
