/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package elquinto;

import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.Random;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaView;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author tomaa
 */
public class ElQuintoUI extends javax.swing.JFrame {

    ArrayList<Integer> numeros = new ArrayList<>();
    ArrayList<Integer> numerosAlmacenamiento = new ArrayList<>();
    ArrayList<String> Opciones = new ArrayList<String>();
    ArrayList<String> Pistas = new ArrayList<String>();
    Pantalla2 pantalla2;

    
    


    /*esto es un ArrayList. Lo he utilizado para almacenar de forma dinámica valores numéricos que mas adelante uso.*/
    /**
     * Creates new form ElQuintoUI
     */
    public ElQuintoUI() {

        initComponents();
        ganar.setVisible(false);
        pantalla2 = new Pantalla2(this);
        
        jButton2.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        numero1 = new javax.swing.JLabel();
        numero2 = new javax.swing.JLabel();
        numero4 = new javax.swing.JLabel();
        numero3 = new javax.swing.JLabel();
        numero7 = new javax.swing.JLabel();
        numero6 = new javax.swing.JLabel();
        numero9 = new javax.swing.JLabel();
        numero8 = new javax.swing.JLabel();
        numero10 = new javax.swing.JLabel();
        numero5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        aleatorio1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ganar = new javax.swing.JPanel();
        ganarBoton = new javax.swing.JButton();
        ganarTexto = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        AcercaDe = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jDialog1.setMinimumSize(new java.awt.Dimension(600, 400));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setMinimumSize(new java.awt.Dimension(600, 400));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("ElQuinto es un juego de rol narrativo y estratégico inspirado en mundos \nfantásticos y mecánicas clásicas de juegos como Dungeons & Dragons y\ntítulos de aventura interactiva. Diseñado para ofrecer una experiencia \ninmersiva, ElQuinto permite a los jugadores construir sus personajes, \ntomar decisiones que impactan la historia y desarrollar habilidades \núnicas mientras enfrentan desafíos que pondrán a prueba su ingenio, \nvalor y creatividad.");
        jTextArea1.setEnabled(false);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 123, 410, 141));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomaa\\Downloads\\Sin título.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 299, -1));

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 292, -1, -1));

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(217, 238, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(440, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(440, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(440, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numero1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numero1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero1.setText("x");
        numero1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 67, 57));

        numero2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numero2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero2.setText("x");
        numero2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(numero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 67, 57));

        numero4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numero4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero4.setText("x");
        numero4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(numero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 67, 57));

        numero3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numero3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero3.setText("x");
        numero3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(numero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 67, 57));

        numero7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numero7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero7.setText("x");
        numero7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(numero7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 67, 57));

        numero6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numero6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero6.setText("x");
        numero6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(numero6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 67, 57));

        numero9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numero9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero9.setText("x");
        numero9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(numero9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 67, 57));

        numero8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numero8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero8.setText("x");
        numero8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(numero8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 67, 57));

        numero10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numero10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero10.setText("x");
        numero10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(numero10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 67, 57));

        numero5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numero5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero5.setText("x");
        numero5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(numero5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 67, 57));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 130, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("GENERAR CARTILLA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 160, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("GENERAR NUMERO");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 140, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("NUMERO ALEATORIO");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 200, 40));

        aleatorio1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        aleatorio1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        aleatorio1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        aleatorio1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(aleatorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 200, 80));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 110, -1));

        jLabel2.setText("VENTANA NICKNAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "a", "b", "ñ", "c" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 120, 20));

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, -1));

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 110, -1));

        jLabel3.setText("VENTANA EMERGENTE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, 20));

        jButton8.setText("jButton8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, 20));

        jLabel4.setText("VENTANA CON OPCIONES");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 20));

        ganar.setMaximumSize(new java.awt.Dimension(440, 300));
        ganar.setMinimumSize(new java.awt.Dimension(440, 300));
        ganar.setPreferredSize(new java.awt.Dimension(440, 300));
        ganar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ganarBoton.setText("jButton3");
        ganarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ganarBotonActionPerformed(evt);
            }
        });
        ganar.add(ganarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 100, 40));

        ganarTexto.setText("HAS GANADO");
        ganar.add(ganarTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 90, 40));

        AcercaDe.setText("Acerca de");
        AcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcercaDeActionPerformed(evt);
            }
        });

        jMenuItem1.setText("¿Que es?");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        AcercaDe.add(jMenuItem1);

        jMenuItem2.setText("Sala");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        AcercaDe.add(jMenuItem2);

        jMenuBar1.add(AcercaDe);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ganar, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ganar, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!jButton2.isShowing()) {
            jButton2.setVisible(true);
        }

        JLabel[] etiquetas = {numero1, numero2, numero3, numero4, numero5, numero6, numero7, numero8, numero9, numero10};
        /*
        Aqui he creado un Array normal de tipo JLabel, que almacena los numeros de la cartilla del Bingo que ya estan creados en la interfaz
         */
        for (JLabel etiqueta : etiquetas) {
            etiqueta.setForeground(Color.black);
        }
        //Esto es un buble For-Each. Basicamente misma funcion que un for normal, solo que para controlar arrays (netbenas te lo convierte automaticamente)

        int[] numero = new int[10];
        //Esto es una array de hasta 10 posiciones, que guardara los numeros randomizados no repetidos

        int comprobarA;
        //Esta variable es para comprobar que x numero no este repetido en una Array

        boolean repetido;
        //Este boolean será el que indiqu+e si un valor esta repetido o no

        for (int i = 0; i < numero.length; i++) {
            //este "for" escoge el primer numero de la array "numero"
            do {
                //aqui estamos empezando un do-while, que primero realiza el codigo mostrado, y luego lo realiza en bucle hasta una condición
                comprobarA = (int) (1 + Math.random() * 20);
                //A esta variable se le esta asignando un valor random, de tipo int, desde el numero 1 hasta el numero 20
                repetido = false;
                //aqui estamos asignando el boolean creado anteriormente como default "false" para que repita el bucle while, hasta que repetido sea = true
                for (int j = 0; j < i; j++) {
                    //este for recorre por completo todo el array, para comrpobar que no existan valores iguales
                    if (comprobarA == numero[j]) {
                        //este if es para comprobar si el numero aleatorio "comprobarA" es igual a cualquiera del array "numero"
                        repetido = true;
                        //se asigna repetido como true, repitiendo el bucle do-while
                        break;
                        //al encontrarse un duplicado, el bucle for (int j) se finaliza garcias al "break", y se repite el do-while
                    }
                }
            } while (repetido /*==true*/);
            //esta es la condicion del do-while, que se repetira hasta que repetido == false
            numero[i] = comprobarA;
            //aqui finalmente estamops asignando el valor unico al array

        }

        for (int i = 0; i < etiquetas.length; i++) {
            etiquetas[i].setText(String.valueOf(numero[i]));
            //este for es para asignar los numeros del array "numero" al array "etiquetas"
        }

        aleatorio1.setText("");
        //vacia JLabel "aleatorio"
        numeros.clear();
        //vacia ArrayList "numeros"
        numerosAlmacenamiento.clear();

    }//GEN-LAST:event_jButton1ActionPerformed


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        JLabel[] etiquetas = {numero1, numero2, numero3, numero4, numero5, numero6, numero7, numero8, numero9, numero10};
        //Nuevamente, aqui he creado un Array normal de tipo JLabel, que almacena los numeros de la cartilla del Bingo que ya estan creados en la interfaz
        int nuevoNumero;
        //este int sera para asignarlo al ArrayList
        if (numeros.size() == 3) {
            numeros.clear();
            aleatorio1.setText("");
            //este if hara que, si el ArrayList "numeros" posee mas de 3 posiciones, que se elimine el mismo y ponga el JLabel aleatorio sin texto
        }

        do {
            nuevoNumero = (int) (1 + Math.random() * 20);
            //genera un número aleatorio entre 1 y 20.
        } while (numerosAlmacenamiento.contains(nuevoNumero));
        //verifica si el número ya existe en la lista.

        numeros.add(nuevoNumero);
        //aqui estamos añadiendo los valores random unicos en el ArrayList numeros
        numerosAlmacenamiento.add((nuevoNumero));
        //aqui estamos añadiendo los valores random unicos en el ArrayList numeros, que sirve para que no se repitan los numeros

        switch (numeros.size()) {
            //este switch actua dependiendo de el tamaño del ArrayList "numeros"
            case 1: {
                aleatorio1.setText(String.valueOf(numeros.get(0)));
                break;
            }
            case 2: {
                aleatorio1.setText(String.valueOf(numeros.get(0) + " " + numeros.get(1)));
                break;
            }
            case 3: {
                aleatorio1.setText(String.valueOf(numeros.get(0) + " " + numeros.get(1) + " " + numeros.get(2)));
                break;
            }
        }
        
        

        for (int i = 0; i < numeros.size(); i++) {
            for (int j = 0; j < etiquetas.length; j++) {
                int numero = (numeros.get(i));
                int etiqueta = Integer.parseInt(etiquetas[j].getText());
                if (numero == etiqueta) {
                    etiquetas[j].setForeground(Color.white);
                    //este if es para seleccionar numeros iguales a los de la cartilla y pone de color blanco
                }
            }
        }
        int contador = 0;
        for (int i = 0; i < etiquetas.length; i++) {

            if (etiquetas[i].getForeground().equals(Color.white)) {
                contador++;
                if (contador == 10) {
                    ganar.setVisible(true);
                    jPanel1.setVisible(false);
                    break;
                    
                }
            }
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void ganarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ganarBotonActionPerformed
        // TODO add your handling code here:
        JLabel[] etiquetas = {numero1, numero2, numero3, numero4, numero5, numero6, numero7, numero8, numero9, numero10};
        /*
        Aqui he creado un Array normal de tipo JLabel, que almacena los numeros de la cartilla del Bingo que ya estan creados en la interfaz
         */
        for (JLabel etiqueta : etiquetas) {
            etiqueta.setForeground(Color.black);
        }
        for (JLabel etiqueta : etiquetas) {
            etiqueta.setText("x");
        }
        aleatorio1.setText("");
        //vacia JLabel "aleatorio"
        numeros.clear();
        //vacia ArrayList "numeros"
        numerosAlmacenamiento.clear();
        ganar.setVisible(false);
        jButton2.setVisible(false);
        
        
        jPanel1.setVisible(true);

    }//GEN-LAST:event_ganarBotonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MyIcon icon = new MyIcon();
        
    
    Opciones.add ("opcion A");
        Opciones.add ("opcion B");
            Opciones.add ("opcion C");
                Opciones.add ("opcion D");
    
    
    
    int seleccion = JOptionPane.showOptionDialog(null,
            "Elige una opcion", "Titulo lol",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            icon,
            Opciones.toArray(),
            Opciones.get(0));



    }//GEN-LAST:event_jButton3ActionPerformed

    private void AcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcercaDeActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_AcercaDeActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
       
        pantalla2.setVisible(true);
      pantalla2.combo(jComboBox1.getSelectedItem().toString());
        
        
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String path ="C:/Users/tomaa/Downloads/Music/Deșteaptă-te, române - Himno nacional de Rumania (letra).mp3";
        Media media = new Media(new File(path).toURI().toString());
        MediaPlayer mediaPlayer = new MediaPlayer(media);
        mediaPlayer.setAutoPlay(true);
        MediaView mediaView = new MediaView(mediaPlayer);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String path ="C:/Users/tomaa/Downloads/Music/Deșteaptă-te, române - Himno nacional de Rumania (letra).mp3";
        Media media = new Media(new File(path).toURI().toString());
        MediaPlayer mediaPlayer = new MediaPlayer(media);
        mediaPlayer.stop();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog("Introduce tu nickname");
        JOptionPane.showMessageDialog(null, "hola " + nombre);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, 
                "Mensaje dentro de la ventana",
        "Mensaje de la barra de titulo",
        JOptionPane.ERROR_MESSAGE);
        
        int respuesta = JOptionPane.showConfirmDialog(null,
                "¿Eres mayor de edaad?",
                "Confirma",
                JOptionPane.YES_NO_CANCEL_OPTION);
        JOptionPane.showMessageDialog(null,"Has respondido: " + String.valueOf(respuesta));
        
        Pistas.add("Baby");
        Pistas.add("Verde");
        Pistas.add("Azul");
        Pistas.add("Roja");
        Pistas.add("Negra");
        MyIcon icon = new MyIcon();
        String Color_pista =
                (String) JOptionPane.showInputDialog(null,
                        "Selecciona una pista",
                        "Astun",
                        JOptionPane.DEFAULT_OPTION,
                        icon,
                        Pistas.toArray(),
                        Pistas.get(0));
        Pistas.clear();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElQuintoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElQuintoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElQuintoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElQuintoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElQuintoUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AcercaDe;
    private javax.swing.JLabel aleatorio1;
    private javax.swing.JPanel ganar;
    private javax.swing.JButton ganarBoton;
    private javax.swing.JLabel ganarTexto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel numero1;
    private javax.swing.JLabel numero10;
    private javax.swing.JLabel numero2;
    private javax.swing.JLabel numero3;
    private javax.swing.JLabel numero4;
    private javax.swing.JLabel numero5;
    private javax.swing.JLabel numero6;
    private javax.swing.JLabel numero7;
    private javax.swing.JLabel numero8;
    private javax.swing.JLabel numero9;
    // End of variables declaration//GEN-END:variables
}
