/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bibliotecarealinterfaz;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author tomaa
 */
public class UI extends javax.swing.JFrame {

    int mouseX, mouseY;
    ;
    Libros libro = new Libros();
    SerializacionCRUD sc = new SerializacionCRUD();
    

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        usuarioText.setOpaque(false);
        passwordText.setOpaque(false);
        usuarioText.setBackground(new java.awt.Color(0, 0, 0, 1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        isbnText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tituloText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        categoriaText = new javax.swing.JTextField();
        precioText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        paginasText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        exitBaseDeDatos = new javax.swing.JLabel();
        tablaAccion = new javax.swing.JLabel();
        ayudaAccion = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        ingresarAccion = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        leerAccion = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        passwordText = new javax.swing.JPasswordField();
        jSeparator6 = new javax.swing.JSeparator();
        usuarioLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        usuarioText = new javax.swing.JTextField();
        exitRegister = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        jDialog1.setLocationByPlatform(true);
        jDialog1.setMaximumSize(new java.awt.Dimension(836, 583));
        jDialog1.setMinimumSize(new java.awt.Dimension(836, 583));
        jDialog1.setUndecorated(true);
        jDialog1.setPreferredSize(new java.awt.Dimension(836, 583));
        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(836, 583));
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        isbnText.setText("Ingrese el ISBN aquí");
        isbnText.setBorder(null);
        isbnText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isbnTextMouseClicked(evt);
            }
        });
        isbnText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnTextActionPerformed(evt);
            }
        });
        jPanel1.add(isbnText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 330, -1));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("TITULO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 330, 20));

        tituloText.setText("Ingrese el TITULO aquí");
        tituloText.setBorder(null);
        jPanel1.add(tituloText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 330, -1));

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("CATEGORIA");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 330, 20));

        categoriaText.setText("Ingrese el CATEGORIA aquí");
        categoriaText.setBorder(null);
        jPanel1.add(categoriaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 330, -1));

        precioText.setText("Ingrese el PRECIO aquí");
        precioText.setBorder(null);
        jPanel1.add(precioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 330, -1));

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("PRECIO");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 330, 20));

        paginasText.setText("Ingrese el NUMERO DE PAGINAS aquí");
        paginasText.setBorder(null);
        jPanel1.add(paginasText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 330, 20));

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("NUMERO DE PAGINAS");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 330, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 340, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 340, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 340, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 340, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 340, 10));

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("ISBN");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 330, 20));

        jPanel12.setBackground(new java.awt.Color(0, 243, 255));
        jPanel12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel12MouseDragged(evt);
            }
        });
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel12MousePressed(evt);
            }
        });
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitBaseDeDatos.setBackground(new java.awt.Color(0, 243, 255));
        exitBaseDeDatos.setFont(new java.awt.Font("Lucida Console", 0, 30)); // NOI18N
        exitBaseDeDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitBaseDeDatos.setText("X");
        exitBaseDeDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBaseDeDatos.setOpaque(true);
        exitBaseDeDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBaseDeDatosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBaseDeDatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBaseDeDatosMouseExited(evt);
            }
        });
        jPanel12.add(exitBaseDeDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 0, 30, 30));

        tablaAccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tablaAccion.setText("jLabel1");
        tablaAccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaAccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tablaAccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tablaAccionMouseExited(evt);
            }
        });
        jPanel12.add(tablaAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 70, 30));

        ayudaAccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ayudaAccion.setText("jLabel1");
        ayudaAccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ayudaAccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ayudaAccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ayudaAccionMouseExited(evt);
            }
        });
        jPanel12.add(ayudaAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 69, 30));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 30));

        jPanel14.setBackground(new java.awt.Color(204, 255, 255));
        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 5, true));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LOGS");
        jPanel14.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 30));

        jScrollPane2.setOpaque(false);

        logArea.setEditable(false);
        logArea.setColumns(20);
        logArea.setRows(5);
        logArea.setToolTipText("");
        logArea.setBorder(null);
        logArea.setOpaque(false);
        jScrollPane2.setViewportView(logArea);

        jPanel14.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 320, 460));

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 340, 500));

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Leelawadee", 1, 28)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("BASE DE DATOS BIBLIOTECA");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 490, 30));

        jPanel17.setBackground(new java.awt.Color(48, 247, 247));
        jPanel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(121, 225, 251), 1, true));
        jPanel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ingresarAccion.setBackground(new java.awt.Color(48, 247, 247));
        ingresarAccion.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        ingresarAccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresarAccion.setText("INGRESAR");
        ingresarAccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarAccionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ingresarAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ingresarAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 100, 30));

        jPanel19.setBackground(new java.awt.Color(48, 247, 247));
        jPanel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(121, 225, 251), 1, true));
        jPanel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel20.setBackground(new java.awt.Color(48, 247, 247));
        jPanel20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(121, 225, 251), 1, true));
        jPanel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel19Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel19Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 100, 30));

        jPanel21.setBackground(new java.awt.Color(48, 247, 247));
        jPanel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(121, 225, 251), 1, true));
        jPanel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        leerAccion.setBackground(new java.awt.Color(48, 247, 247));
        leerAccion.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        leerAccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leerAccion.setText("LEER");
        leerAccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leerAccionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(leerAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(leerAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, -1, -1));

        jPanel22.setBackground(new java.awt.Color(48, 247, 247));
        jPanel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(121, 225, 251), 1, true));
        jPanel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel14.setBackground(new java.awt.Color(48, 247, 247));
        jLabel14.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("MODIFICAR");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, -1, -1));

        jPanel23.setBackground(new java.awt.Color(48, 247, 247));
        jPanel23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(121, 225, 251), 1, true));
        jPanel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setBackground(new java.awt.Color(48, 247, 247));
        jLabel6.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ELIMINAR");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, -1, -1));

        jDialog1.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 670));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(840, 351));
        setMinimumSize(new java.awt.Dimension(840, 351));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(840, 351));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordText.setText("Ingrese un USUARIO");
        passwordText.setBorder(null);
        passwordText.setMinimumSize(new java.awt.Dimension(1, 30));
        passwordText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordTextMousePressed(evt);
            }
        });
        passwordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextActionPerformed(evt);
            }
        });
        jPanel9.add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));
        jPanel9.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 510, 20));

        usuarioLabel.setBackground(new java.awt.Color(0, 0, 0));
        usuarioLabel.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        usuarioLabel.setText("USUARIO");
        jPanel9.add(usuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        passwordLabel.setBackground(new java.awt.Color(0, 0, 0));
        passwordLabel.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        passwordLabel.setText("CONTRASEÑA");
        jPanel9.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));
        jPanel9.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 510, 20));

        usuarioText.setText("Ingrese un USUARIO");
        usuarioText.setBorder(null);
        usuarioText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuarioTextMousePressed(evt);
            }
        });
        usuarioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTextActionPerformed(evt);
            }
        });
        jPanel9.add(usuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 510, 30));

        exitRegister.setBackground(new java.awt.Color(0, 243, 255));
        exitRegister.setFont(new java.awt.Font("Malgun Gothic", 1, 30)); // NOI18N
        exitRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitRegister.setText("X");
        exitRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitRegister.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                exitRegisterMouseDragged(evt);
            }
        });
        exitRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitRegisterMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitRegisterMousePressed(evt);
            }
        });
        jPanel9.add(exitRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 40, 40));

        jPanel10.setOpaque(false);
        jPanel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel10MouseDragged(evt);
            }
        });
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel10MousePressed(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(48, 247, 247));
        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(121, 225, 251), 1, true));
        jPanel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setBackground(new java.awt.Color(48, 247, 247));
        jLabel4.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("INGRESAR");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 70));

        jLabel3.setBackground(new java.awt.Color(48, 247, 247));
        jLabel3.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INGRESAR");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 100, 30));

        jPanel13.setBackground(new java.awt.Color(48, 247, 247));
        jPanel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(121, 225, 251), 1, true));
        jPanel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, -1));

        jPanel15.setBackground(new java.awt.Color(0, 204, 255));
        jPanel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 159, 186), 5, true));
        jPanel15.setForeground(new java.awt.Color(0, 204, 255));
        jPanel15.setOpaque(false);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 350));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 550));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(39, 216, 216));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 210, 550));

        jPanel7.setBackground(new java.awt.Color(22, 181, 181));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 210, 550));

        jPanel8.setBackground(new java.awt.Color(11, 167, 167));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 550));

        jPanel5.setBackground(new java.awt.Color(48, 247, 247));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 210, 550));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isbnTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnTextActionPerformed

    private void usuarioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTextActionPerformed

    private void exitRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitRegisterMouseEntered
        // TODO add your handling code here:
        exitRegister.setOpaque(true);
        exitRegister.setBackground(Color.red);
    }//GEN-LAST:event_exitRegisterMouseEntered

    private void exitRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitRegisterMouseExited
        // TODO add your handling code here:
        exitRegister.setOpaque(false);
        exitRegister.setBackground(new java.awt.Color(0, 0, 0, 1));

    }//GEN-LAST:event_exitRegisterMouseExited

    private void exitRegisterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitRegisterMousePressed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_exitRegisterMousePressed

    private void exitRegisterMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitRegisterMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_exitRegisterMouseDragged

    private void jPanel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MousePressed
        // TODO add your handling code here:

        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanel10MousePressed

    private void jPanel10MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_jPanel10MouseDragged

    private void usuarioTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioTextMousePressed
        // TODO add your handling code here:
        if (usuarioText.getText().equals("Ingrese un USUARIO")) {
            usuarioText.setText("");
            usuarioText.setForeground(Color.black);
        }
        if (String.valueOf(passwordText.getPassword()).isEmpty()) {
            passwordText.setText("Ingrese un USUARIO");
        }

    }//GEN-LAST:event_usuarioTextMousePressed

    private void passwordTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordTextMousePressed
        // TODO add your handling code here:
        if (String.valueOf(passwordText.getPassword()).equals("Ingrese un USUARIO")) {
            passwordText.setText("");

        }
        if (usuarioText.getText().isEmpty()) {
            usuarioText.setText("Ingrese un USUARIO");
        }
    }//GEN-LAST:event_passwordTextMousePressed

    private void passwordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextActionPerformed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jLabel4MousePressed

    private void exitBaseDeDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBaseDeDatosMouseClicked
        // TODO add your handling code here:
        jDialog1.setVisible(false);
    }//GEN-LAST:event_exitBaseDeDatosMouseClicked

    private void exitBaseDeDatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBaseDeDatosMouseEntered
        // TODO add your handling code here:
        exitBaseDeDatos.setBackground(Color.red);
    }//GEN-LAST:event_exitBaseDeDatosMouseEntered

    private void exitBaseDeDatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBaseDeDatosMouseExited
        // TODO add your handling code here:
        exitBaseDeDatos.setBackground(new Color(0, 243, 255));
    }//GEN-LAST:event_exitBaseDeDatosMouseExited

    private void jPanel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanel12MousePressed

    private void jPanel12MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        jDialog1.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_jPanel12MouseDragged

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void ingresarAccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarAccionMouseClicked
        // TODO add your handling code here:
        Libros libro2 = new Libros();
        libro2.setISBN(isbnText.getText());
        libro2.setTitulo(tituloText.getText());
        libro2.setCategoria(categoriaText.getText());
        libro2.setPrecio(precioText.getText());
        libro2.setNumPAG(paginasText.getText());

        
        sc.agregarLibro(libro2);
        logArea.setText(logArea.getText()+ "El usuario a creado un libro con ISBN: " + libro2.getISBN() + "\n");

        isbnText.setText("");
        tituloText.setText("");
        categoriaText.setText("");
        precioText.setText("");
        paginasText.setText("");


    }//GEN-LAST:event_ingresarAccionMouseClicked

    private void leerAccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leerAccionMouseClicked
        // TODO add your handling code here:
        String libroABuscar = (isbnText.getText());
        if (sc.leerLibro(libroABuscar)==null) {
            JOptionPane.showMessageDialog(null, "error1", "error2", JOptionPane.ERROR_MESSAGE);
            return;
        }
        libro = sc.leerLibro(libroABuscar);
        isbnText.setText(libro.getISBN());
        tituloText.setText(libro.getTitulo());
        categoriaText.setText(libro.getCategoria());
        precioText.setText(libro.getPrecio());
        paginasText.setText(libro.getNumPAG());
        
        
        

    }//GEN-LAST:event_leerAccionMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void isbnTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isbnTextMouseClicked
        // TODO add your handling code here:
        if (isbnText.getText().equals("Ingrese el ISBN aquí")) {
            isbnText.setText("");
        }
    }//GEN-LAST:event_isbnTextMouseClicked

    private void ayudaAccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ayudaAccionMouseEntered
        // TODO add your handling code here:
        ayudaAccion.setOpaque(true);
        ayudaAccion.setBackground(Color.red);
    }//GEN-LAST:event_ayudaAccionMouseEntered

    private void ayudaAccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ayudaAccionMouseExited
        // TODO add your handling code here:
        ayudaAccion.setOpaque(false);
        ayudaAccion.setBackground(new Color(0, 0, 0, 1));
    }//GEN-LAST:event_ayudaAccionMouseExited

    private void tablaAccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAccionMouseEntered
        // TODO add your handling code here:
        tablaAccion.setOpaque(true);
        tablaAccion.setBackground(Color.red);
    }//GEN-LAST:event_tablaAccionMouseEntered

    private void tablaAccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAccionMouseExited
        // TODO add your handling code here:
        tablaAccion.setOpaque(false);
        tablaAccion.setBackground(new Color(0, 0, 0, 0));
    }//GEN-LAST:event_tablaAccionMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ayudaAccion;
    private javax.swing.JTextField categoriaText;
    private javax.swing.JLabel exitBaseDeDatos;
    private javax.swing.JLabel exitRegister;
    private javax.swing.JLabel ingresarAccion;
    private javax.swing.JTextField isbnText;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel leerAccion;
    private javax.swing.JTextArea logArea;
    private javax.swing.JTextField paginasText;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JTextField precioText;
    private javax.swing.JLabel tablaAccion;
    private javax.swing.JTextField tituloText;
    private javax.swing.JLabel usuarioLabel;
    private javax.swing.JTextField usuarioText;
    // End of variables declaration//GEN-END:variables
}
